### ISSUE TITLE
ledger_index  type in the ledger response of clio differs with rippled.

### ISSUE THREAD

**Issue by mounikakun** [XRPLF/clio#1014]
request:
`{"method": "ledger", "params": [{"transactions": false, "expand": false, "owner_funds": false, "ledger_index": "validated", "api_version": 2, "ledger_hash": "46BF445D434BE4332D5C466CDCE624B34E04AD9105D18C3F5788972A5AF7416C", "Fee": 20}]}
`

Rippled:
`{
  'account_hash': '41EDE981EBDD8469C2B6194CE2CACABF1235B2CE9BC4F73486C7A7CD46F32B82',
  'close_flags': 0,
  'close_time': 754880530,
  'close_time_human': '2023-Dec-03 01:02:10.000000000 UTC',
  'close_time_iso': '2023-12-03T01:02:10Z',
  'close_time_resolution': 10,
  'closed': True,
  'ledger_hash': '46BF445D434BE4332D5C466CDCE624B34E04AD9105D18C3F5788972A5AF7416C',
  'ledger_index': 2151309,
  'parent_close_time': 754880522,
  'parent_hash': 'DFAA20C7B700353581BB96E58B85DFF5F4DB25B015A5D6A185DD88FAE74691C7',
  'total_coins': '99999027323338605',
  'transaction_hash': '2A073E7C13C5A61C4BBCFF062F1D92760195FEBC59FAD34EDFB4D5F5DDED10B9'
}`

Clio:
`{
  'account_hash': '41EDE981EBDD8469C2B6194CE2CACABF1235B2CE9BC4F73486C7A7CD46F32B82',
  'close_flags': 0,
  'close_time': 754880530,
  'close_time_human': '2023-Dec-03 01:02:10.000000000 UTC',
  'close_time_resolution': 10,
  'close_time_iso': '2023-12-03T01:02:10Z',
  'ledger_hash': '46BF445D434BE4332D5C466CDCE624B34E04AD9105D18C3F5788972A5AF7416C',
  'ledger_index': '2151309',
  'parent_close_time': 754880522,
  'parent_hash': 'DFAA20C7B700353581BB96E58B85DFF5F4DB25B015A5D6A185DD88FAE74691C7',
  'total_coins': '99999027323338605',
  'transaction_hash': '2A073E7C13C5A61C4BBCFF062F1D92760195FEBC59FAD34EDFB4D5F5DDED10B9',
  'closed': True
}`

**Comment by kennyzlei** [comment]
related rippled pr
- https://github.com/XRPLF/rippled/pull/4820
