### ISSUE TITLE
ripple_path_find with non existent destination account error differs from rippled.

### ISSUE THREAD

**Issue by mounikakun** [XRPLF/clio#1015]
request
`{
    "method": "ripple_path_find",
    "params": [
        {
            "destination_account": "r9cZA1mLK5R5Am25ArfXFmqgNwjZgnfk59",
            "destination_amount": {
                "currency": "USD",
                "issuer": "rEWbChTNMTZojoD9Se2ZovqL7p9uFfLjfw",
                "value": "0.001"
            },
            "source_account": "rEWbChTNMTZojoD9Se2ZovqL7p9uFfLjfw",
            "source_currencies": [
                {
                    "currency": "XRP"
                },
                {
                    "currency": "USD"
                }
            ]
        }
    ]
}`

Rippled:
`{
    "result": {
        "error": "srcActNotFound",
        "error_code": 67,
        "error_message": "Source account not found.",
        "ledger_current_index": 2116855,
        "request": {
            "command": "ripple_path_find",
            "destination_account": "r9cZA1mLK5R5Am25ArfXFmqgNwjZgnfk59",
            "destination_amount": {
                "currency": "USD",
                "issuer": "rEWbChTNMTZojoD9Se2ZovqL7p9uFfLjfw",
                "value": "0.001"
            },
            "source_account": "rEWbChTNMTZojoD9Se2ZovqL7p9uFfLjfw",
            "source_currencies": [
                {
                    "currency": "XRP"
                },
                {
                    "currency": "USD"
                }
            ]
        },
        "status": "error",
        "validated": false
    }
}`

Clio:
`{
    "result": {
        "error": "actNotFound",
        "error_code": 19,
        "error_message": "Account not found.",
        "request": {
            "command": "ripple_path_find",
            "destination_account": "r9cZA1mLK5R5Am25ArfXFmqgNwjZgnfk59",
            "destination_amount": {
                "currency": "USD",
                "issuer": "rEWbChTNMTZojoD9Se2ZovqL7p9uFfLjfw",
                "value": "0.001"
            },
            "source_account": "rEWbChTNMTZojoD9Se2ZovqL7p9uFfLjfw",
            "source_currencies": [
                {
                    "currency": "XRP"
                },
                {
                    "currency": "USD"
                }
            ]
        },
        "status": "error",
        "type": "response",
        "forwarded": true
    },
    "warnings": [
        {
            "id": 2001,
            "message": "This is a clio server. clio only serves validated data. If you want to talk to rippled, include 'ledger_index':'current' in your request"
        }
    ]
}`

**Comment by cindyyan317** [comment]
ETL rippled is different from the compared rippled.
