### ISSUE TITLE
Clio should not crash if ETL not available 

### ISSUE THREAD

**Issue by cindyyan317** [XRPLF/clio#1073]
We found Clio crashed when it was not in ETL rippled's secure gateway IP list. 
![Screenshot 2024-01-03 at 18 19 15](https://github.com/XRPLF/clio/assets/120398799/b39865af-82c1-47b0-aa18-c5102bda870c)
![Screenshot 2024-01-03 at 18 19 42](https://github.com/XRPLF/clio/assets/120398799/23d9a6af-6a8a-48ca-bf56-71e3bbf27dd8)

Clio should not crash when ETL is not available.

**Comment by godexsoft** [comment]
Code was updated in #1171 
We can't reproduce with the new code.
