### ISSUE TITLE
DB raises error : "Batch too large" when writing account_tx

### ISSUE THREAD

**Issue by cindyyan317** [XRPLF/clio#1074]
We encountered a ledger with 193 transactions (devnet 3050793), the account_tx needs to be inserted 1693 items for that ledger.
Clio got error: 
`"2024-01-04 10:06:10.875576 (cassandra/impl/RetryPolicy.h:61) [0x00007fe800ff9700] Backend:ERR Cassandra write error: invokeHelper: Batch too large, current retries 37, retrying in 1024 milliseconds"` 

The log from the DB side is :
`ERROR [Native-Transport-Requests-6] 2024-01-04 10:52:30,715 BatchStatement.java:352 - Batch for [clio.account_tx] is of size 119.039KiB, exceeding specified threshold of 50.000KiB by 69.039KiB. (see batch_size_fail_threshold_in_kb)
 `
We need to fix it

**Comment by godexsoft** [comment]
Fixed via #1077
