### ISSUE TITLE
feat: add user version of `feature` RPC

### ISSUE THREAD

**Issue by intelliot** [XRPLF/clio#1131]
- https://github.com/XRPLF/rippled/pull/4781
- Users should be able to use `feature` to determine whether an amendment is `supported` by Clio
- Docs for admin version of the method: https://xrpl.org/feature.html

**Comment by godexsoft** [comment]
Removed 2.2 milestone for now as we can't implement it until support is added to `libxrpl` and that is not happening until after 2.2.0.
Replacing with #1440 until then.
