### ISSUE TITLE
Failed to forward request to p2p node

### ISSUE THREAD

**Issue by PaulMoney** [XRPLF/clio#1186]
Hello, currently I'm facing this kind of error, when I want to send a request with `'ledger_index': 'current'`

The error which I get while running Node.js app:

```
RippledError: Failed to forward request to p2p node
  ...
  data: {
    error: 'failedToForward',
    error_code: 90,
    error_message: 'Failed to forward request to p2p node',
    status: 'error',
    type: 'response',
    id: 0,
    request: {
      command: 'tx',
      transaction: '2A6FE7C3E29CBECC299C7739402376863F5A91D2691855096C2A589ED19C4BE1',
      ledger_index: 'current',
      api_version: 1,
      id: 0
    },
    warnings: [ [Object] ]
  }
}
```

Currently used Clio version: `1.0.4.libxrpl.upgrade` and my config file looks like this:
```
{
    "database":
    {
        "type":"cassandra",
        "cassandra":
        {
            "contact_points":"127.0.0.1",
            "port":9042,
            "keyspace":"clio",
            "replication_factor":1,
            "table_prefix":"",
            "max_requests_outstanding":25000,
            "threads":8
        }
    },
    "etl_sources":
    [
        {
            "ip":"172.29.0.6",
            "ws_port":"6005",
            "grpc_port":"50051"
        }
    ],
    "dos_guard":
    {
        "whitelist":["20.215.81.102"]
    },
    "server":{
        "ip":"0.0.0.0",
        "port":51233,
        "max_queue_size":500
    },
    "log_channels": [
        {
            "channel": "Backend",
            "log_level": "fatal"
        },
        {
            "channel": "WebServer",
            "log_level": "info"
        },
        {
            "channel": "Subscriptions",
            "log_level": "info"
        },
        {
            "channel": "RPC",
            "log_level": "error"
        },
        {
           "channel": "ETL",
           "log_level": "debug"
        },
        {
            "channel": "Performance",
            "log_level": "trace"
        }
    ],
    "log_level":"debug",
    "log_to_console": true,
    "log_directory":"/opt/clio/etc/clio_log",
    "log_rotation_size": 2048,
    "log_directory_max_size": 10200,
    "log_rotation_hour_interval": 12,
    "extractor_threads":8,
    "read_only":false,
    "api_version": {
        "min": 1, // Minimum API version supported (could be 1 or 2)
        "max": 2, // Maximum API version supported (could be 1 or 2, but >= min)
        "default": 1 // Clio behaves the same as rippled by default
    }
}

```

P.s ETL source is working properly, as Clio fetches and stores new ledgers into DB. Also, when I switch to `'ledger_index': 'validated'` everything works fine.
Any ideas why it is unable to forward this request ?

**Comment by kuznetsss** [comment]
Hi @PaulMoney, thanks for reporting this. 

I have tried your request in the [Websocket Tool](https://xrpl.org/websocket-api-tool.html#tx) and it worked fine:
<img width="1319" alt="Screenshot 2024-02-15 at 18 53 35" src="https://github.com/XRPLF/clio/assets/15742918/bef9215c-e78b-44ed-a199-34cd21046c05">

Probably the issue is caused by the outdated version of Clio. Please consider upgrading Clio (don't forget that moving from version `1.0.4` to `2.x.x` requires [database migration](https://github.com/XRPLF/clio/tree/clio_migrator%402.0.0)).

**Comment by PaulMoney** [comment]
@kuznetsss Hi, the problem was not related to the version of the Clio server but to the `port_ws_public` protocol. In the `etl source`, I had specified only `wss` and not `ws`. Therefore, I added `ws` to that stanza, and now Clio sends requests to Rippled without any issues.

**Comment by kuznetsss** [comment]
Hi @PaulMoney, thanks for sharing! It will be useful if someone else gets the same issue.

Unfortunately SSL doesn't work in ETL sources even in the latest release `2.1.0`. The good news is I have already opened a PR #1171 fixing it so SSL should be working fine in the next release `2.2.0`.
