### ISSUE TITLE
Support data deletion

### ISSUE THREAD

**Issue by cjcobb23** [XRPLF/clio#12]
Use TTL

**Comment by cjcobb23** [comment]
This is implemented, but needs rigorous testing

**Comment by cjcobb23** [comment]
We originally tried to implement this like online_delete in rippled, where data is just deleted automatically, but I don't think this is appropriate for a cluster of nodes, since it is not easy to coordinate who is doing the deletion. I think this should be an admin RPC comand, that starts the deletion.

**Comment by kuznetsss** [comment]
None of this worked, so we deleted this code. Once ETL is rewritten it will be supported out of box.
