### ISSUE TITLE
Look into X-Forwarded-For (Version: 2.1.0)

### ISSUE THREAD

**Issue by godexsoft** [XRPLF/clio#1207]
## Summary
Look into supporting [X-Forwarded-For](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Forwarded-For).

## Motivation
It would be useful to support proxies and load balancers.

## Solution
Leverage the X-Forwarded-For header.

**Comment by godexsoft** [comment]
There needs to be a list of whitelisted IPs (proxy for example) for which this header will be used. If we allow everyone to use the header we basically grant unlimited usage to anyone sending random IPs.

**Comment by kennyzlei** [comment]
related rippled PR https://github.com/XRPLF/rippled/pull/4009

**Comment by cindyyan317** [comment]
After initial investigation, we decide to support it in Clio to provide safer traffic limitation.  The actual implementation will be done by https://github.com/XRPLF/clio/issues/1641.
