### ISSUE TITLE
Use new base58 parser (Version: 2.1.0)

### ISSUE THREAD

**Issue by godexsoft** [XRPLF/clio#1211]
## Summary
`rippled` introduced a new, faster parser for base58: https://github.com/XRPLF/rippled/pull/4327

## Motivation
15x faster than the previous implementation. It shows about 10% speedup for RPC commands in `rippled` and should be for Clio too.

## Solution
Use the new parser.

## Paths Not Taken
- Write our own parser.
- Use a library
- Leave as is

**Comment by cindyyan317** [comment]
Link with #88

**Comment by godexsoft** [comment]
Looks like nothing to do in Clio in order to support this.
The fast algorithm is automatically used when compiled outside of MSVC (relies on __int128 found in both gcc and clang).
Clio already uses `libxrpl`'s base58 functions and does not use other 3rd party library for this nor introduces a custom parser for base58.
