### ISSUE TITLE
Improve developer docs

### ISSUE THREAD

**Issue by godexsoft** [XRPLF/clio#1235]
Other than our READMEs and repo docs we now have generated developer docs.
The are automatically deployed to https://xrplf.github.io/clio with each merged PR.
It would be nice to apply some styling and content changes to those too.

**Comment by godexsoft** [comment]
@maria-robobug something you could help with? 🙇

**Comment by maria-robobug** [comment]
I'll try to see if I have some bandwith to look into this next week 👍🏾 .
