### ISSUE TITLE
Throw error and exit when config is invalid

### ISSUE THREAD

**Issue by shichengripple001** [XRPLF/clio#1279]
when clio is started with invlid config, clio process won't die, it continues to run and will not respond to API calls. This makes it very hard to find out what went wrong.

A fix should be made to detect invalid config and exit when process boot up.

**Comment by kuznetsss** [comment]
Could you please clarify what do you mean by invalid config?
Clio will not start if some of required fields are missing or some fields have wrong type.

**Comment by godexsoft** [comment]
Looks strange to me. I think your experience may be caused by some external misconfiguration rather than Clio's config. I'd like to reproduce it if you can explain how. If there is a real bug, we will of course fix it 👍

**Comment by godexsoft** [comment]
Also, please follow our bug issue template next time 🙏 If you would have followed it you would have posted the parts of config you think are invalid, the version you used, logs and other useful info.

**Comment by shichengripple001** [comment]
when "forwarding_cache_timeout": 0.5, is missing, clio seemed to stuck in a strange status and not able to accept any request.

**Comment by kuznetsss** [comment]
`forwarding_cache_timeout` only affects forwarding part and if the option is missing in just turns off cache. I tried to run Clio without the option and it worked fine.  I think as @godexsoft said there is a misconfiguration somewhere else (rippled or database) in your setup.

**Comment by godexsoft** [comment]
@shichengripple001 any update on this? should we close it?

**Comment by shichengripple001** [comment]
closing it
