### ISSUE TITLE
Improve documentation

### ISSUE THREAD

**Issue by cjcobb23** [XRPLF/clio#13]
We need a descriptive README with step by step instructions to build and run.

**Comment by cjcobb23** [comment]
We also need an example config that describes the different options

**Comment by lathanbritz** [comment]
thanks for the update to the build steps for the C compile, up and running here now.

**Comment by godexsoft** [comment]
Documentation already have been enhanced since this issue was created. More enhancements will be added as time goes on and clio evolves. Closing for now.
