### ISSUE TITLE
Don't clone handler on each request

### ISSUE THREAD

**Issue by kuznetsss** [XRPLF/clio#1345]
Currently we are copying handler to process each request:
https://github.com/XRPLF/clio/blob/7fcd3e48bd4f2080a4433d79d6925dc0bb0bdf8f/src/rpc/common/AnyHandler.hpp#L56-L58

We could avoid it and return a handler by reference or shared pointer.

**Comment by cindyyan317** [comment]
By using shared_ptr, we may introduce performance overhead in critical path.

The current handlers actually don’t have any member variables. The cost of copying should be low. In addition, if we don’t copy the handler, we implicitly disallow the handler having member variables. As framework, we shall give the handler writer the flexibility to use member variables.     

After weighting the gain and loss, we decided to copy the handler for now.
