### ISSUE TITLE
Update doxygen to 1.12

### ISSUE THREAD

**Issue by kuznetsss** [XRPLF/clio#1431]
Doxygen 1.11 has been released. We need to upgrade it in our CI. Also 1.11 produces error on checking Clio, we need to fix it as well.

**Comment by godexsoft** [comment]
Doxygen 1.11.0 breaks `@ref` generation for our mainpage. Reported issue: https://github.com/doxygen/doxygen/issues/10906

**Comment by godexsoft** [comment]
Doxygen 1.12 is out and seem to have fixed our issue. Let's start using it
