### ISSUE TITLE
Allow Clio continue running when there is one etl rippled available

### ISSUE THREAD

**Issue by cindyyan317** [XRPLF/clio#1444]
## Summary
With the config **allow_no_etl** being false, Clio can not start when there is any etl rippled not available. It is too strict. As long as there is one rippled can work, Clio can start.

## Motivation
Clio can work with single rippled as etl. Clio should not fail to start when there is workable rippled existing. The impact of **allow_no_etl** is not necessarily wide.

## Solution
Only throw error when all etl rippled not available.

**Comment by kuznetsss** [comment]
Probably the behaviour you described should be by default. If `allow_no_etl` is true Clio should be able to run without working ETL. And maybe we should introduce another flag `strict_etl_check` to be able to force current behaviour.
