### ISSUE TITLE
cache JSON

### ISSUE THREAD

**Issue by cjcobb23** [XRPLF/clio#145]
When responding to a request, the bulk of our time is spent serializing to JSON. This is exacerbated even further for the cases where we serialize first to rippled JSON, then convert to boost JSON.

We should cache the JSON representation of commonly requested objects and transactions. For transactions, this is easy, but for objects, its a bit more difficult, because we don't have an identifier. The object ID is not sufficient, because an object changes over time but it's ID stays the same. 

There are a number of ways to go about this. We could just hash the whole blob. We could use uint256 and just invalidate modified entries on ledger update. We could store the ledger sequence with the uin256 and make sure we are getting the right object. etc.

**Comment by natenichols** [comment]
We tried this in #155, but I went ahead and closed it due to increases in latency observed.. We should revisit this branch https://github.com/cjcobb23/clio/tree/json_cache_pr when the time comes to redesign it.

**Comment by godexsoft** [comment]
Cache in general is part of our plan moving forward. There is no one true design at the moment. We will spend time investigating possibilities and trade offs. Will take the branch above into account. Closing this one for now.
