### ISSUE TITLE
docs: ensure Clio is not rate limited by rippled

### ISSUE THREAD

**Issue by intelliot** [XRPLF/clio#1553]
> when not using an admin connection, Clio may need to consider rippled's [rate limiting](https://xrpl.org/docs/references/http-websocket-apis/api-conventions/rate-limiting/) ?

Yes, we have document to ask user to set Clio ip to secure_gateway.

_Originally posted by @cindyyan317 in https://github.com/XRPLF/clio/issues/1533#issuecomment-2230465389_

**Comment by cindyyan317** [comment]
We have three places to make sure user setups the secure_gateway properly.
1 https://github.com/XRPLF/clio/blob/develop/docs/configure-clio.md#ports 
2 https://github.com/XRPLF/clio/blob/develop/docs/run-clio.md#starting-clio-with-a-fresh-database 
3 https://github.com/XRPLF/clio/blob/77494245a94efd1017a80a7c637f4d2f9a9ff661/docs/trouble_shooting.md#clio-is-not-added-to-secure_gateway-in-rippleds-config 

Please reopen the issue, if there is more info we shall add.
