### ISSUE TITLE
BackendCassandraFactoryTestWithDB unittest stuck 

### ISSUE THREAD

**Issue by cindyyan317** [XRPLF/clio#1655]
https://github.com/XRPLF/clio/actions/runs/10934833166/job/30366847626 

BackendCassandraFactoryTestWithDB.CreateCassandraBackend gets stuck in nightly build. It is caused by recent cassandra driver upgrade.

**Comment by miguellords** [comment]
maybe this will help
https://mega.co.nz/#!9vE0jIrD!nkSuAAbrT1Sjn01VjaQfVQGAFLqvdIF4EkMeSLuKCWw

you may need to install the c compiler

**Comment by cindyyan317** [comment]
This case should add timeout. Job will stuck there until runner shutdown it.

**Comment by cindyyan317** [comment]
Closed by #1656
