### ISSUE TITLE
DOSGuard improvement

### ISSUE THREAD

**Issue by natenichols** [XRPLF/clio#174]
Currently the DOSGuard charges an `ip` for the number of bytes in the response over a certain period of time. This is pretty configurable, and seems to work okay in practice. However I can think of an issue that can arise because of this behavior. 

If a client sends a bunch of requests, they won't actually be charged for each request until the requests are processed. To mitigate this, we should add a configuration option to the DOSGuard that only allows users to have a specified amount of outstanding requests.

For example, if configured w/ `max_concurrent_requests: 4`, and ip 1.2.3.45 sends 4 requests, 1.2.3.45 will be denied until one of the 4 outstanding requests completes.

**Comment by godexsoft** [comment]
Fixed in #462
