### ISSUE TITLE
Fast cache load

### ISSUE THREAD

**Issue by natenichols** [XRPLF/clio#189]
Instead of loading directly from rippled, or directly from the Backend w/ `fetchLedgerPage`, we should persist the latest cache locally, load it from disk, and use that to freshen the cache.

**Comment by cjcobb23** [comment]
Idk about persisting to disk. A new server won't have any cache on disk, and persisting is going to take quite some time (several gbs of data). It would take a while for clio to shutdown if we make this change, and if clio crashes, there's no cache on disk. Plus, if a server is down for a while, the cache on disk will be very stale.

**Comment by cjcobb23** [comment]
new clio nodes should just sync off existing clio nodes

**Comment by godexsoft** [comment]
This was implemented by means of loading the cache from configured peers (other clio nodes). See example-config.json `cache->peers`.
