### ISSUE TITLE
Use Unix domain socket into rippled for local host

### ISSUE THREAD

**Issue by RichardAH** [XRPLF/clio#191]
Rippled should publish a Unix domain socket suited to Clio’s transfer requirements in a well known filesystem location and Clio should look for it by default. If done along with the embedded database then this is a zero config setup which will work out of the box for most users.

**Comment by godexsoft** [comment]
Seems like you are suggesting some changes to `rippled` which is not part of `clio` repo. Closing for now. Feel free to reopen it if I have misunderstood the idea.
