### ISSUE TITLE
account_tx returns `marker` after all transactions have been received

### ISSUE THREAD

**Issue by mukulljangid** [XRPLF/clio#195]
{account=r9m6MwViR4GnUNqoGXGa8eroBrZ9FAPHFS, ledgerIndexMinimum=61400000, ledgerIndexMaximum=61437000, binary=false, forward=false}
lengths:
50
50
50
50
50
34
0
Clio returned marker in the response with 34 transactions, hence the last one has 0.

**Comment by sappenin** [comment]
Just for clarity here on this issue, Clio is returning a `Marker` even when there are no more results to be returned. Reporting mode does _not_ do this, and [per the docs](https://xrpl.org/markers-and-pagination.html#markers-and-pagination) the marker should be `null` when the # of transactions is 0.
