### ISSUE TITLE
Service protection: Cassandra fetch limit per clio node

### ISSUE THREAD

**Issue by sophiax851** [XRPLF/clio#209]
From performance testing of Clio 1.0, Cassandra can support up to 30K/sec total fetches and beyond that, Cassandra node's CPU will exceed 80% of utilization and latency start to getting higher. We need a mechanism to make sure the total reads/sec among all Clio application hosts doesn't exceed 30k.

**Comment by cjcobb23** [comment]
Fixed here: https://github.com/XRPLF/clio/pull/242
