### ISSUE TITLE
account_tx clio response ledger_index_max and ledger_index_min values differ from rippled response.

### ISSUE THREAD

**Issue by mounikakun** [XRPLF/clio#217]

**Comment by mounikakun** [comment]
Here's the sample request:
`{
   "method": "account_tx",
   "params": [
       {
           "account": "rM2ab1Dgd6cKpgfCi6QXCVjf37xcgU7KRf",
           "binary": false,
           "forward": false,
           "ledger_index_max": -1,
           "ledger_index_min": -1,
           "limit":1
       }
   ]
}
`

Link for sample rippled and clio response:

https://ripplelabs.atlassian.net/wiki/spaces/~6244a5228678e900705a63ad/pages/edit-v2/2426503180?draftShareId=35de7fbd-f3bc-405b-9d11-594bc358bc90

**Comment by cjcobb23** [comment]
Fixed here: https://github.com/XRPLF/clio/pull/255

**Comment by godexsoft** [comment]
@cjcobb23 This seems like a different issue from the one solved in #255, please confirm and reopen.

**Comment by cjcobb23** [comment]
That PR refactored parts of the code that were causing this behavior.

**Comment by cjcobb23** [comment]
@ManiMounikaKunasani what is the difference? Can you provide some sample requests and responses please?

**Comment by mounikakun** [comment]
request:
`{ "method": "account_tx", "params": [ { "account": "rM2ab1Dgd6cKpgfCi6QXCVjf37xcgU7KRf", "binary": false, "forward": false, "ledger_index_max": -1, "ledger_index_min": -1, "limit":1 } ] }`

Rippled response:
`{
    "result": {
        "account": "rM2ab1Dgd6cKpgfCi6QXCVjf37xcgU7KRf",
        "ledger_index_max": 23553814,
        "ledger_index_min": 23332877,
        "limit": 1,
        "status": "success",
        "transactions": [],
        "validated": true
    }
}`

Clio response:
`{
    "result": {
        "limit": 1,
        "ledger_index_min": 21377274,
        "ledger_index_max": 23553815,
        "transactions": [],
        "account": "rM2ab1Dgd6cKpgfCi6QXCVjf37xcgU7KRf",
        "validated": true,
        "status": "success"
    },
    "warnings": [
        {
            "id": 2001,
            "message": "This is a clio server. clio only serves validated data. If you want to talk to rippled, include 'ledger_index':'current' in your request"
        }
    ]
}`

The issue is `ledger_index_min` and `ledger_index_max` for rippled and Clio are different. It might be an expected response but it was marked as bug and issue was raised. Please confirm if this discrepancy is expected or not.

Apart from the above one, `inLedger` is missing in the `tx` of Clio response.
Sample request:
`{ "method": "account_tx", "params": [ { "account": "rGtoopKHE9Yb2Fh31jKZdcCDZC4FvpbvCK", "binary": false, "forward": false, "ledger_index_max": -1, "ledger_index_min": -1, "limit" : 1} ] }`

Also, please clarify on what was fixed in this issue?

**Comment by godexsoft** [comment]
@ManiMounikaKunasani 
The difference in `ledger_index_min/max` is normal and expected. It's just returning whatever min and max ledgers we have data for (in both rippled and clio). It's ok to have saved data for slightly different ledger ranges.

The `inLedger` field is a copy of `ledger_index` which we already provide in the response.
Since the `tx` JSON object format is not defined/documented, we are free to ignore `inLedger` and only return `ledger_index`.
