### ISSUE TITLE
Missing  'limit' parameter in the clio response of "account_lines", "account_channels", "account_objects", "account_offers" requests.

### ISSUE THREAD

**Issue by mounikakun** [XRPLF/clio#221]
Here is the link for sample requests I have tested on

[](https://docs.google.com/document/d/13QoYtKHHcn6-IV0o4taOMXFZEGeTImRNMEUmx8ji2AU/edit
)

**Comment by mounikakun** [comment]
Sample requests I have tested:

https://docs.google.com/document/d/13QoYtKHHcn6-IV0o4taOMXFZEGeTImRNMEUmx8ji2AU/edit

Sample rippled and clio request responses:

https://ripplelabs.atlassian.net/wiki/spaces/~6244a5228678e900705a63ad/pages/edit-v2/2426503180?draftShareId=35de7fbd-f3bc-405b-9d11-594bc358bc90

**Comment by officialfrancismendoza** [comment]
@ManiMounikaKunasani I was able to find the "limit" parameter for testing account_lines when sending to s2, unless I am misunderstanding the issue. Attached a screenshot below showing the limit parameter grepped from the output

The command I ran was: 
`curl -H 'Content-Type: application/json' -d '{   "method": "account_lines",   "params": [       {           "account": "rpRq4fC6kfeS7cR42YL5ZJMTNSj9noedU7",           "ledger_index": "validated",           "limit": 2       }   ]}' https://s2-clio.ripple.com:51233/`

![image](https://user-images.githubusercontent.com/47958858/192069488-6813a4f9-aa8e-4d0c-80ff-359faaba76c3.png)

**Comment by officialfrancismendoza** [comment]
@ManiMounikaKunasani just to double-check, I made a request, but on the sample account found in the XRPL documentation for account_limit [here](https://xrpl.org/account_lines.html) and grepped the limit in the Clio response. As the account for the sample account_limit in the [Clio requests google doc](https://docs.google.com/document/d/13QoYtKHHcn6-IV0o4taOMXFZEGeTImRNMEUmx8ji2AU/edit) did not exist, I got fuller output this time, but they both still returned limit

The command I ran was:
`curl -H 'Content-Type: application/json' -d'{    "method": "account_lines",    "params": [        {            "account": "r9cZA1mLK5R5Am25ArfXFmqgNwjZgnfk59",            "ledger_index": "validated",            "limit":2        }    ]}' https://s2-clio.ripple.com:51233/`

![image](https://user-images.githubusercontent.com/47958858/192069774-84f9b133-ef3f-421b-bdee-e6ae8211fe40.png)
![image](https://user-images.githubusercontent.com/47958858/192069678-51dc5785-ea5a-4e0a-a121-e7e76fe5e114.png)

**Comment by mounikakun** [comment]
@officialfrancismendoza I don't mean the limit parameter in lines of account_lines response.

Rippled response has 'limit' in 'result'  and 'result['lines']' whereas Clio response has 'limit' only in 'result['lines']'
Rippled response:

{
    "result": {
        "account": "rpRq4fC6kfeS7cR42YL5ZJMTNSj9noedU7",
        "ledger_hash": "6BEC3C637BD68336CE7D523CB78C41E56F412EC263C2A30C80A983B65DB84957",
        "ledger_index": 22005564,
        **"limit": 2,**
        "lines": [
            {
                "account": "r97U4iT9m8Q2FeYnAQ1gFKGFDoKe8E7Rh",
                "balance": "0",
                "currency": "LKR",
                **"limit": "0",
                "limit_peer": "90"**,
                "no_ripple": true,
                "no_ripple_peer": false,
                "quality_in": 0,
                "quality_out": 0
            },
            {
                "account": "r97U4iT9m8Q2FeYnAQ1gFKGFDoKe8E7Rh",
                "balance": "0",
                "currency": "KZT",
                **"limit": "0",
                "limit_peer": "90",**
                "no_ripple": true,
                "no_ripple_peer": false,
                "quality_in": 0,
                "quality_out": 0
            }
        ],
        "marker": "0695AE2A0EEED3AD57082972F7BFE76B4F4C44C1B07EA0D5C2AAE9306BBEF45D,0",
        "status": "success",
        "validated": true
    }
}

Clio response:
{
    "result": {
        "account": "rpRq4fC6kfeS7cR42YL5ZJMTNSj9noedU7",
        "ledger_hash": "10BC6F36E8ED046AA3CBFE2637151DB2BB7F642879C054C0745926DCF455ABA0",
        "ledger_index": 22005559,
        "lines": [
            {
                "account": "r97U4iT9m8Q2FeYnAQ1gFKGFDoKe8E7Rh",
                "balance": "0",
                "currency": "LKR",
                **"limit": "0",
                "limit_peer": "90"**,
                "quality_in": 0,
                "quality_out": 0,
                "no_ripple": true,
                "no_ripple_peer": false
            },
            {
                "account": "r97U4iT9m8Q2FeYnAQ1gFKGFDoKe8E7Rh",
                "balance": "0",
                "currency": "KZT",
                **"limit": "0",
                "limit_peer": "90"**,
                "quality_in": 0,
                "quality_out": 0,
                "no_ripple": true,
                "no_ripple_peer": false
            },
            {
                "account": "raeR1nAGkMm18hHpUz1ZP6wGKLA4WCh8rX",
                "balance": "0",
                "currency": "ASP",
                **"limit": "0",
                "limit_peer": "100"**,
                "quality_in": 0,
                "quality_out": 0,
                "no_ripple": true,
                "no_ripple_peer": false
            },
            {
                "account": "r97U4iT9m8Q2FeYnAQ1gFKGFDoKe8E7Rh",
                "balance": "0",
                "currency": "JEP",
                **"limit": "0",
                "limit_peer": "90"**,
                "quality_in": 0,
                "quality_out": 0,
                "no_ripple": true,
                "no_ripple_peer": false
            },
            {
                "account": "r97U4iT9m8Q2FeYnAQ1gFKGFDoKe8E7Rh",
                "balance": "0",
                "currency": "ASP",
                **"limit": "0",
                "limit_peer": "390"**,
                "quality_in": 0,
                "quality_out": 0,
                "no_ripple": true,
                "no_ripple_peer": false
            },
            {
                "account": "r97U4iT9m8Q2FeYnAQ1gFKGFDoKe8E7Rh",
                "balance": "0",
                "currency": "LBP",
                **"limit": "0",
                "limit_peer": "90"**,
                "quality_in": 0,
                "quality_out": 0,
                "no_ripple": true,
                "no_ripple_peer": false
            },
            {
                "account": "r97U4iT9m8Q2FeYnAQ1gFKGFDoKe8E7Rh",
                "balance": "0",
                "currency": "ISK",
                **"limit": "0",
                "limit_peer": "90"**,
                "quality_in": 0,
                "quality_out": 0,
                "no_ripple": true,
                "no_ripple_peer": false
            },
            {
                "account": "raeR1nAGkMm18hHpUz1ZP6wGKLA4WCh8rX",
                "balance": "0",
                "currency": "USD",
                **"limit": "0",
                "limit_peer": "390"**,
                "quality_in": 0,
                "quality_out": 0,
                "no_ripple": true,
                "no_ripple_peer": false
            },
            {
                "account": "r97U4iT9m8Q2FeYnAQ1gFKGFDoKe8E7Rh",
                "balance": "0",
                "currency": "USD",
                **"limit": "0",
                "limit_peer": "390"**,
                "quality_in": 0,
                "quality_out": 0,
                "no_ripple": true,
                "no_ripple_peer": false
            },
            {
                "account": "r97U4iT9m8Q2FeYnAQ1gFKGFDoKe8E7Rh",
                "balance": "0",
                "currency": "GEL",
                **"limit": "0",
                "limit_peer": "390"**,
                "quality_in": 0,
                "quality_out": 0,
                "no_ripple": true,
                "no_ripple_peer": false
            }
        ],
        "marker": "C826BFD70CF4E65D4AD474B168A16FE98F1BB08D27BCADBF076883FB179A2DC7,0",
        "validated": true,
        "status": "success"
    },
    "warnings": [
        {
            "id": 2001,
            "message": "This is a clio server. clio only serves validated data. If you want to talk to rippled, include 'ledger_index':'current' in your request"
        }
    ]
}

**Comment by mounikakun** [comment]
"account_channels" without limit parameter in the request returns 'limit' in the clio response.

request:
`{
    "method": "account_channels",
    "params": [{
        "account": "rn7VxEfBxsih12HDnNQN8sSkY6QW4L7vJd",
        "ledger_index": "validated"
    }]
}`

Rippled response:
`{
    "result": {
        "account": "rn7VxEfBxsih12HDnNQN8sSkY6QW4L7vJd",
        "channels": [],
        "ledger_hash": "BFF179A8D931D3C39C1307B2B8FB07E71C46577147D86CEBD7C5A232020D6C2B",
        "ledger_index": 23531781,
        "status": "success",
        "validated": true
    }
}`

Clio response:
`{
    "result": {
        "account": "rn7VxEfBxsih12HDnNQN8sSkY6QW4L7vJd",
        "channels": [],
        "limit": 50,
        "ledger_hash": "99E6BD0895AF72665DC475F5054F588999DF8BEA9514A6077A3A5BBFE95E589A",
        "ledger_index": 23531774,
        "validated": true,
        "status": "success"
    },
    "warnings": [
        {
            "id": 2001,
            "message": "This is a clio server. clio only serves validated data. If you want to talk to rippled, include 'ledger_index':'current' in your request"
        }
    ]
}`

Issue exists for account_lines and account_offers  also.

**Comment by godexsoft** [comment]
@ManiMounikaKunasani please see #418 discussion about always adding `limit` to the response in `clio`.
