### ISSUE TITLE
"noripple_check" without 'ledger_index:current' returns "invalidParams" error.

### ISSUE THREAD

**Issue by mounikakun** [XRPLF/clio#223]
Sample request and response:
`{
   "method": "noripple_check",
   "params": [
       {
           "account": "rpRq4fC6kfeS7cR42YL5ZJMTNSj9noedU7",
           "role": "gateway",
           "transactions": true,
           "limit": 11
       }
   ]
}`

`{
    "result": {
        "error": "invalidParams",
        "error_code": 31,
        "error_message": "rpcDoesNotRequireLimit",
        "status": "error",
        "type": "response",
        "request": {
            "method": "noripple_check",
            "params": [
                {
                    "account": "rpRq4fC6kfeS7cR42YL5ZJMTNSj9noedU7",
                    "role": "gateway",
                    "transactions": true,
                    "limit": 11
                }
            ]
        },
        "warnings": [
            "This is a clio server. clio only serves validated data. If you want to talk to rippled, include 'ledger_index':'current' in your request"
        ]
    },
    "warnings": [
        "This is a clio server. clio only serves validated data. If you want to talk to rippled, include 'ledger_index':'current' in your request",
        "Too many requests"
    ]
}`

**Comment by cjcobb23** [comment]
Add a limit here: https://github.com/XRPLF/clio/blob/379c89fb02d750652335c8864f70cde9870eb271/src/rpc/RPC.cpp#L189
