### ISSUE TITLE
"server_info" of Clio returns scientific notation values for "base_fee_xrp", "reserve_base_xrp", "reserve_inc_xrp".

### ISSUE THREAD

**Issue by mounikakun** [XRPLF/clio#224]
Sample response:

`{
    "result": {
        "info": {
            "complete_ledgers": "19350165-19351861",
            "counters": {
                "rpc": {
                    "account_info": {
                        "started": "3",
                        "finished": "3",
                        "errored": "0",
                        "forwarded": "3",
                        "duration_us": "4109"
                    },
                    "subscribe": {
                        "started": "2",
                        "finished": "2",
                        "errored": "0",
                        "forwarded": "0",
                        "duration_us": "69"
                    },
                    "server_info": {
                        "started": "6",
                        "finished": "6",
                        "errored": "0",
                        "forwarded": "0",
                        "duration_us": "19810"
                    },
                    "account_currencies": {
                        "started": "8",
                        "finished": "0",
                        "errored": "8",
                        "forwarded": "0",
                        "duration_us": "0"
                    }
                },
                "subscriptions": {
                    "ledger": 0,
                    "transactions": 0,
                    "transactions_proposed": 0,
                    "manifests": 2,
                    "validations": 2,
                    "account": 0,
                    "accounts_proposed": 0,
                    "books": 0
                }
            },
            "load_factor": 1,
            "clio_version": "0.3.0-b1",
            "validation_quorum": 8,
            "rippled_version": "1.9.1",
            "validated_ledger": {
                "age": 2,
                "hash": "7655EEEE320904835A0FFD3E26F2058935999A03D5129713A7309E45FAC2BB4B",
                "seq": 19351861,
                "base_fee_xrp": 1E-5,
                "reserve_base_xrp": 1E1,
                "reserve_inc_xrp": 2E0
            }
        },
        "cache": {
            "size": 8516769,
            "is_full": true,
            "latest_ledger_seq": 19351861
        },
        "etl": {
            "etl_sources": [
                {
                    "validated_range": "19349695-19351861",
                    "is_connected": "1",
                    "ip": "127.0.0.1",
                    "ws_port": "6006",
                    "grpc_port": "50051",
                    "last_msg_age_seconds": "0"
                }
            ],
            "is_writer": true,
            "read_only": false,
            "last_publish_age_seconds": "1"
        },
        "note": "This is a clio server. If you want to talk to rippled, include \"ledger_index\":\"current\" in your request",
        "validated": true,
        "status": "success",
        "warning": [
            "Too many requests"
        ]
    }
}`

**Comment by cjcobb23** [comment]
`base_fee_xrp` is allowed to be in scientific notation

**Comment by cjcobb23** [comment]
https://xrpl.org/server_info.html

**Comment by mounikakun** [comment]
To validate clio server_info I don't have any reference. It would be helpful if there's something I can refer to.

**Comment by cjcobb23** [comment]
`complete_ledgers`, `validated_ledger`, `validation_quorum`, `load_factor` should match rippled at least in format
