### ISSUE TITLE
support ip ranges in whitelist

### ISSUE THREAD

**Issue by cjcobb23** [XRPLF/clio#244]

**Comment by godexsoft** [comment]
It would be useful to provide a description what actually needs to be done here.
From what we can tell it's probably something like this:

```
"dos_guard":
{
    "whitelist":["192.168.0.*", "192.168.1.[1-5]"]
}
```

I imagine this can only be really useful for some local network where the router assigns IP addresses using DHCP (e.g. allow all users on local network to access `clio` running on some machine in the network).
@cjcobb23 if you have a minute, please elaborate on what kind of format you had in mind for this. Thanks

**Comment by injaelee** [comment]
Let's support CIDR notations for the whitelist. There are many references to whitelisting IP addresses in many frameworks / platforms. Here's one reference. (cc: @godexsoft @officialfrancismendoza)
- [EC2 Network Access](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/authorizing-access-to-an-instance.html)

**Comment by officialfrancismendoza** [comment]
@injaelee I was assuming classless IPv4 + CIDR based on your comment in the slack. That said, in the process of making additional unit tests to handle the following cases: [reserve IPv4 Addresses](https://www.tutorialspoint.com/ipv4/ipv4_reserved_addresses.htm), [no continuous 0's and 1's for host addresses](https://community.cisco.com/t5/switching/valid-host-address/td-p/1413517), etc.
![image](https://user-images.githubusercontent.com/47958858/216129719-09120caf-1aa4-4181-84e7-20a46ddc2de2.png)
