### ISSUE TITLE
Idea proposal : could we have a lite-clio server than could run on a raspberry pi 4 8Gb

### ISSUE THREAD

**Issue by paco2773** [XRPLF/clio#248]
Hi there,
I'm a raspberry pi 4 hobbyiste user, It like to know if it could be possible to have a version of lite-clio server to run on a Pi4 with ARM CPU and 8 GB of RAM, ROM could be scale with micro-SD HD card upto 128 GB and more.

And with a growing number of rapsberry Pi 4 enthusiam all around the globe, this could served well the ripple network or the future root network also.

Also this could permit smaller carbon footprint for the both network, because the raspberry pi 4 is very low energy consuming wise.

Thanks for considering my resquest.

Have a nice days
Francois Drolet

**Comment by cjcobb23** [comment]
You can run a clio server today with the cache off and the data stored elsewhere (some remote cassandra cluster) on a raspberry pi. With no cache, the latency of certain RPCs can be a bit high (for book_offers in particular).

If you want to also store data on the raspberry pi, that's probably not possible today. You'd need to run ScyllaDB or Cassandra on the pi.

**Comment by legleux** [comment]
> You'd need to run ScyllaDB or Cassandra on the pi.

You'd have to build them yourself and these database's default settings make my machine sweat so I'm pretty sure it's not possible.
So if Clio is not caching, and the DB isn't local, is there a point even?

**Comment by cjcobb23** [comment]
We currently don't cache transaction based requests at all, and these perform fine (`tx` `account_tx` `ledger`). I would suspect `account_info` will do fine without caching as well, since its just a single db request. It's things like `book_offers`, `account_lines`, `account_objects`, etc, which result in many database queries per request that would suffer a lot from no caching.

**Comment by godexsoft** [comment]
Seeing there is no responses or further interest let's close this.
