### ISSUE TITLE
Add `start_sequence` to the example config

### ISSUE THREAD

**Issue by Mwni** [XRPLF/clio#250]
The `start_sequence` parameter currently is not documented. It should at least be included in the example configuration files. But then the issue is, which example value for the sequence should be picked?

**Comment by cjcobb23** [comment]
Good question. I see 3 options here:

1. Allow start_sequence to be `-1`, in which case its ignored
2. Figure out how to add comments to json
3. Document all of the config options in the README somewhere.

What do you think?

**Comment by Mwni** [comment]
Since options 1 and 2 are hacks: option 3. I would welcome documentation for the config in general.
Is a .toml based config feasible?

**Comment by cjcobb23** [comment]
I agree that 3 is best. .toml is probably feasible, haven't looked into it.
