### ISSUE TITLE
“account_tx” with unfunded account do not return actMalformed error.

### ISSUE THREAD

**Issue by mounikakun** [XRPLF/clio#261]
The address specified in the account field of the request does not correspond to an account in the ledger.
Expected output: `actMalformed` error
Actual output: No error
Suggested fix: return account not found and update documentation.

Sample request:
`{
   "method": "account_tx",
   "params": [
       {
           "account": "rB7LiohHNiAnP4t1QK2RNL4YGat57sCDMz",
           "binary": false,
           "forward": false,
           "ledger_index_max": -1,
           "ledger_index_min": -1
       }
   ]
}
`

**Comment by godexsoft** [comment]
@ManiMounikaKunasani can't reproduce with current `develop`.
For the account in the sample request both `rippled` and `clio` return success with empty transactions.
If i change a letter in the account to make it invalid - i get actMalformed from both `rippled` and `clio`.

**Comment by legleux** [comment]
Getting same response as of 29f1f860d860433913278784a5361379e8cc69a4
```
curl rippled:5005 -d'{ "method": "account_tx", "params": [ { "account": "rB7LiohHNiAnP4t1QK2RNL4YGat57sCDMz", "binary": false, "forward": false, "ledger_index
_max": -1, "ledger_index_min": -1 } ] } '
{"result":{"account":"rB7LiohHNiAnP4t1QK2RNL4YGat57sCDMz","ledger_index_max":33861998,"ledger_index_min":33861311,"limit":0,"status":"success","transactions":[],"validated":true}}
```
Clio:
```
curl clio:8080 -d'{ "method": "account_tx", "params": [ { "account": "rB7LiohHNiAnP4t1QK2RNL4YGat57sCDMz", "binary": false, "forward": false, "ledger_index
_max": -1, "ledger_index_min": -1 } ] } '
{"result":{"ledger_index_min":33833664,"ledger_index_max":33862003,"transactions":[],"account":"rB7LiohHNiAnP4t1QK2RNL4YGat57sCDMz","validated":true,"status":"success"},"warnings":[{"id":2001,"message":"This is a clio server. clio only serves validated data. If you want to talk to rippled, include 'ledger_index':'current' in your request"}]}
```
