### ISSUE TITLE
“account_tx” with invalid ledger_index_max returns "invalidParams" instead of "lgrIdxsInvalid"

### ISSUE THREAD

**Issue by mounikakun** [XRPLF/clio#263]
The request specifies a ledger_index_max that is before the ledger_index_min.
Expected response:`lgrIdxsInvalid`
Actual response: `invalidParams`

Sample request:
`{
   "method": "account_tx",
   "params": [
       {
           "account": "r4s7P9WUU6AZ9DB315GWKtBaaDji9Zst8h",
           "binary": false,
           "forward": false,
           "ledger_index_max": 21085176,
           "ledger_index_min": -1
       }
   ]
}`

**Comment by mounikakun** [comment]
“account_tx” with Either the request specifies a ledger_index_max that is before the ledger_index_min, and the server does not have a validated ledger range because it is not synced with the network.
Expected response: `lgrIdxsInvalid`
Actual response: `invalidParams`

Sample request:
`{
   "method": "account_tx",
   "params": [
       {
           "account": "r4s7P9WUU6AZ9DB315GWKtBaaDji9Zst8h",
           "binary": false,
           "forward": false,
           "ledger_index_max": 19399132,
           "ledger_index_min": -1
       }
   ]
}`

**Comment by legleux** [comment]
as of 29f1f860d860433913278784a5361379e8cc69a4
```
"method": "account_tx", "params": [{"account": "rhYtqWeTaAiMv8qTnke98HsTxy9XZBdp5X", "binary": false, "forward": false, "ledger_index_ma
x": 21085176, "ledger_index_min": -1, "Fee": "20"}]}'
```
returns `lgrIdxMalformed` and the `error_message`s are different:
rippled: `"Ledger indexes invalid."`
clio: `ledgerSeqMaxOutOfRange`
```
{"result":{"error":"lgrIdxMalformed","error_code":58,"error_message":"ledgerSeqMaxOutOfRange","status":"error","type":"response","request":{"method":"account_tx","params":[{"account":"rhYtqWeTaAiMv8qTnke98HsTxy9XZBdp5X","binary":false,"forward":false,"ledger_index_max":21085176,"ledger_index_min":-1,"Fee":"20"}]}},"warnings":[{"id":2001,"message":"This is a clio server. clio only serves validated data. If you want to talk to rippled, include 'ledger_index':'current' in your request"}]}
```

**Comment by godexsoft** [comment]
@officialfrancismendoza looks like all we need to do is remove "ledgerSeqMaxOutOfRange" in `RPCHelpers.cpp`.

**Comment by godexsoft** [comment]
@legleux Ok, so apparently the response from rippled is completely different from clio atm.:
``` 
"error": "lgrIdxsInvalid",
"error_code": 57,
"error_message": "Ledger indexes invalid.",
```

@officialfrancismendoza Let's use `rpcLGR_IDXS_INVALID` without custom message instead so we get exactly what `rippled` responds with.
