### ISSUE TITLE
“gateway_balances” with unfunded account do not return "actNotFound" error.

### ISSUE THREAD

**Issue by mounikakun** [XRPLF/clio#270]
Expected response: `actNotFound`
Actual response:No error

Sample request:
`{
   "method": "gateway_balances",
   "params": [
       {
           "account": "rhKKk5KB8LuxmjvTSA7r3iYmJXGqnno7Mf",
           "ledger_index": "validated"
       }
   ]
}
`

**Comment by cjcobb23** [comment]
fixed in https://github.com/XRPLF/clio/pull/382
