### ISSUE TITLE
“gateway_balances” with invalid account in hot wallet do not return error.

### ISSUE THREAD

**Issue by mounikakun** [XRPLF/clio#271]
One or more of the addresses specified in the hotwallet field is not the address of an account holding currency issued by the account from the request.
Expected response: `invalidHotWallet`
Actual response: No error

Sample request:
`{
    "method": "gateway_balances",
    "params": [
        {
            "account": "rMwjYedjc7qqtKYVLiAccJSmCwih4LnE2q",
            "hotwallet": [
                "rhKKk5KB8LuxmjvTSA7r3iYmJXGqnno7M"
            ],
            "ledger_index": "validated",
            "strict": true
        }
    ]
}`

**Comment by mounikakun** [comment]
Issue still exists. After the fix, response has `actNotFound` error instead of `invalidHotWallet`

**Comment by cjcobb23** [comment]
But the account is not found though? `rMwjYedjc7qqtKYVLiAccJSmCwih4LnE2q` does not exist on the ledger. According to the docs, this is a proper response:
https://xrpl.org/gateway_balances.html
```
actNotFound - The [Address](https://xrpl.org/basic-data-types.html#addresses) specified in the account field of the request does not correspond to an account in the ledger.
```
Can you test with an account that actually exists on the ledger?

**Comment by mounikakun** [comment]
Even for ledger account the response has `actNotFound` error.

Request:
`{ "method": "gateway_balances", "params": [ { "account": "rMwjYedjc7qqtKYVLiAccJSmCwih4LnE2q", "hotwallet": [ "rn7VxEfBxsih12HDnNQN8sSkY6QW4L7vJd" ], "ledger_index": "validated", "strict": true } ] }`

Rippled response:
`{
    "result": {
        "account": "rMwjYedjc7qqtKYVLiAccJSmCwih4LnE2q",
        "ledger_hash": "F92A0AF9505A31913475C9B63588A2CFC025F947B90B96B76D5F7C2B00342EE3",
        "ledger_index": 23553196,
        "status": "success",
        "validated": true
    }
}`

Clio response:
`{
    "result": {
        "error": "actNotFound",
        "error_code": 19,
        "error_message": "Account not found.",
        "status": "error",
        "type": "response",
        "request": {
            "method": "gateway_balances",
            "params": [
                {
                    "account": "rMwjYedjc7qqtKYVLiAccJSmCwih4LnE2q",
                    "hotwallet": [
                        "rn7VxEfBxsih12HDnNQN8sSkY6QW4L7vJd"
                    ],
                    "ledger_index": "validated",
                    "strict": true
                }
            ]
        }
    },
    "warnings": [
        {
            "id": 2001,
            "message": "This is a clio server. clio only serves validated data. If you want to talk to rippled, include 'ledger_index':'current' in your request"
        }
    ]
}`

**Comment by godexsoft** [comment]
I can definitely reproduce the discrepancy shown above.

This happens when the account is not actually on the ledger (`accNotFound` is correct). In this case `clio` _correctly_ returns `accNotFound` but `rippled` seems to ignore that fact and just return empty data.
Same goes for when "hotwallet" is specified. If it's invalid `clio` return `invalidHotWallet` but `rippled` will return the same empty dataset ignoring the hotwallet.

One thing i noticed while looking into this is that in `clio` we are checking `hot_wallet` not `hotwallet` so that part needs fixing for sure.
I'm yet to find out how to test this fully. Once done i'll add more info here.
