### ISSUE TITLE
“ledger_entry” with the request improperly specified the deposit_preauth.owner sub-field do not return "malformedOwner"

### ISSUE THREAD

**Issue by mounikakun** [XRPLF/clio#273]
Expected response: `malformedOwner`
Actual response: `invalidParams`

Sample request:
`{
  "method": "ledger_entry",
  "params": [{
    "deposit_preauth": {
      "owner": "rf1BiGeXwwQoi8Z2ueFYTEXSwuJYfV2Jpna",
      "authorized": "ra5nK24KXen9AHvsdFTKHSANinZseWnPcX"
    },
    "ledger_index": "validated"
  }]
}`

**Comment by officialfrancismendoza** [comment]
To expound on the recurrence: One edge case found by @ManiMounikaKunasani contained a perfectly formatted owner string that was not found. Arguably "malformedOwner" should not be the proper error message to pass here as the request is perfectly formed, but the account owner doesn't exist. 
![image](https://user-images.githubusercontent.com/47958858/204623318-415f0ae1-0f95-4c64-a185-964ce551007d.png)
![image](https://user-images.githubusercontent.com/47958858/204623370-453351c9-1eda-4afd-b44d-1b60f069bf58.png)
![image](https://user-images.githubusercontent.com/47958858/204623412-28e825f8-e393-42e0-8c13-b3ff272cc795.png)

**Comment by officialfrancismendoza** [comment]
@injaelee closing this issue as per our discussion with @godexsoft as to edge case being unclear and code handling cases
