### ISSUE TITLE
“ledger_entry” with request improperly specified a Currency Code field do not return "malformedCurrency"

### ISSUE THREAD

**Issue by mounikakun** [XRPLF/clio#275]
Expected response: `malformedCurrency`
Actual response: `invalidParams`

Sample request:
`{
  "method": "ledger_entry",
  "params": [{
    "ripple_state": {
      "accounts": [
        "rEgAvY1qyEfZxwSaDg5UdLtNQzyvSPEXtV",
        "rhyxmFfxujVTfxBjug37kouzms6YzWpAUy"
      ],
      "currency": "aa"
    },
    "ledger_index": "validated"
  }]
}`

**Comment by officialfrancismendoza** [comment]
@ManiMounikaKunasani there is no dedicated error code for malformedCurrency within ErrorCodes.h. Closing this issue as the plaintext error already returns "malformedCurrency'" and needs no further modification

**Comment by officialfrancismendoza** [comment]
@ManiMounikaKunasani changed the "malformedCurrency" text error to "invalidParams" but don't think this is advisable as we are downgrading from a more specific error message. A custom error code for malformedCurrency does not within rippled's ErrorCodes.h

**Comment by mounikakun** [comment]
@officialfrancismendoza I think there's some misunderstanding here. Expected change from this issue is the `error` in Clio response should be `malformedCurrency` instead of `invalidParams`.

Sample rippled response:
`{
    "result": {
        "error": "malformedCurrency",
        "ledger_hash": "2490B57E90FC49F9F930A1C0E7C31DF253B61F28444A1A0171A515F33E946D60",
        "ledger_index": 23070262,
        "request": {
            "command": "ledger_entry",
            "ledger_index": "validated",
            "ripple_state": {
                "accounts": [
                    "rEgAvY1qyEfZxwSaDg5UdLtNQzyvSPEXtV",
                    "rhyxmFfxujVTfxBjug37kouzms6YzWpAUy"
                ],
                "currency": "aa"
            }
        },
        "status": "error",
        "validated": true
    }
}`

Sample Clio response:
`{
    "result": {
        "error": "invalidParams",
        "error_code": 31,
        "error_message": "malformedCurrency",
        "status": "error",
        "type": "response",
        "request": {
            "method": "ledger_entry",
            "params": [
                {
                    "ripple_state": {
                        "accounts": [
                            "rEgAvY1qyEfZxwSaDg5UdLtNQzyvSPEXtV",
                            "rhyxmFfxujVTfxBjug37kouzms6YzWpAUy"
                        ],
                        "currency": "aa"
                    },
                    "ledger_index": "validated"
                }
            ]
        }
    },
    "warnings": [
        {
            "id": 2001,
            "message": "This is a clio server. clio only serves validated data. If you want to talk to rippled, include 'ledger_index':'current' in your request"
        }
    ]
}`

**Comment by officialfrancismendoza** [comment]
@ManiMounikaKunasani as I have mentioned above, there is no custom error code within Rippled's ErrorCodes.h specifically for malformedCurrency. Unless we are making a modification to Rippled libraries to make an entirely new error code for malformedCurrency, the invalidParams error code was selected as the default. 

Clio differs from Rippled in error reporting as it takes both an error code and a hardcoded string to classify errors, whereas Rippled only takes the latter. I can change the hardcoded string back to "malformedCurrency", but we just end up where we were originally. This does not solve the error code problem, where the default is rpc_INVALID_PARAMS and a "rpc_MALFORMED_CURRENCY" does not exist.

That is originally why I closed the issue and I have expressed the same concerns you had as part of the explanation in the pull request below.  

My next push will include this custom error code within Rippled's ErrorCodes.h, but you'll need CJ to sign off on this. 

![image](https://user-images.githubusercontent.com/47958858/199106919-6a3d980a-d49b-4ef8-a1d8-4899a2b0e7f7.png)

**Comment by godexsoft** [comment]
Taking this one over. 
Will try to modify `RPC::Status` to operate on a `std::variant` of `rippled`'s errors enum as well as `clio`'s own errors enum.
This way we should support both sets of errors (probably as long as `clio`'s enum is a `enum class`).

**Comment by mounikakun** [comment]
Clio response is missing `ledger_hash`,`ledger_index`, `validated`

Rippled response:
`{
    "result": {
        "error": "malformedCurrency",
        "ledger_hash": "AF756E58D568B93B564E8E1A5D9E43CFAAF8C8106F439E0BD893779CC69989DE",
        "ledger_index": 23530782,
        "request": {
            "command": "ledger_entry",
            "ledger_index": "validated",
            "ripple_state": {
                "accounts": [
                    "rEgAvY1qyEfZxwSaDg5UdLtNQzyvSPEXtV",
                    "rhyxmFfxujVTfxBjug37kouzms6YzWpAUy"
                ],
                "currency": "aa"
            }
        },
        "status": "error",
        "validated": true
    }
}`

Clio response:
`{
    "result": {
        "error": "malformedCurrency",
        "error_code": 5000,
        "error_message": "malformedCurrency",
        "status": "error",
        "type": "response",
        "request": {
            "method": "ledger_entry",
            "params": [
                {
                    "ripple_state": {
                        "accounts": [
                            "rEgAvY1qyEfZxwSaDg5UdLtNQzyvSPEXtV",
                            "rhyxmFfxujVTfxBjug37kouzms6YzWpAUy"
                        ],
                        "currency": "aa"
                    },
                    "ledger_index": "validated"
                }
            ]
        }
    },
    "warnings": [
        {
            "id": 2001,
            "message": "This is a clio server. clio only serves validated data. If you want to talk to rippled, include 'ledger_index':'current' in your request"
        }
    ]
}`

**Comment by godexsoft** [comment]
@ManiMounikaKunasani the missing fields noted in the buglist sheet are out of scope for the original issue here so let's open a new one for the missing fields if you think we need them.
