### ISSUE TITLE
“no ripple check” with invalid account returns "invalidParams" instead of "actNotFound"

### ISSUE THREAD

**Issue by mounikakun** [XRPLF/clio#277]
Expected response: `actNotFound`
Actual response: `invalidParams`

Sample request:
`{
   "method": "noripple_check",
   "params": [
       {
           "account": "raeR1nAGkMm18hHpUz1ZP6wGKLA4WCh8rXa",
           "limit": 2,
           "role": "gateway",
           "transactions": true
       }
   ]
}
`

**Comment by godexsoft** [comment]
It was decided not to allow seeds. Closing
