### ISSUE TITLE
“tx” with min_ledger and max_ledger fields of the request are more than 1000 apart returns no error.

### ISSUE THREAD

**Issue by mounikakun** [XRPLF/clio#278]
Expected response: `excessiveLgrRange`
Actual response: No error 
Suggested fix: change the docs for clio to accept infinitely large range

Sample request:
`{
   "method": "tx",
   "params": [
       {
           "transaction": "823C3BB277B19ED2AA7ED20CC2AD62B064CC9A20B59B7C6C5F3821A6A53676A4",
           "binary": false,
           "min_ledger":"19499130",
           "max_ledger": "21007767"
       }
   ]
}`

**Comment by godexsoft** [comment]
Reopening so @ManiMounikaKunasani can close when verified.

**Comment by legleux** [comment]
This issue is resolved but now unless you pass the range as a string you get:
```
{'error': 'invalidParams', 'error_code': 31, 'error_message': 'Invalid field min_ledger, not uint.', 'request': {'meth...', 'min_ledger': '33866512', 'transaction': '95376492DE6B2B3192EAC759A9868F2F85546B9C7251F65FF1DD56D9BD73755A'}]}
```
