### ISSUE TITLE
“ledger” with one or more fields are specified incorrectly do not return "invalidParams".

### ISSUE THREAD

**Issue by mounikakun** [XRPLF/clio#279]
Expected response: `invalidParams`
Actual response: `lgrNotFound`

Sample request:
`{
   "method": "ledger",
   "params": [
       {
           "ledger_index": "ghgj"
       }
   ]
}`

**Comment by officialfrancismendoza** [comment]
@ManiMounikaKunasani I don't think we should downgrade from LGR_NOT_FOUND to invalidParams (as it's less accurate), but have pushed the PR anyway
