### ISSUE TITLE
“ledger” if you specified full  as true, but not connected to the server as an admin do not return "noPermission" error.

### ISSUE THREAD

**Issue by mounikakun** [XRPLF/clio#280]
Expected response: `noPermission`
Actual response: No error
Suggested fix: document on clio part for ledger request.

Sample request:
`{
   "method": "ledger",
   "params": [
       {
           "ledger_index": "validated",
           "accounts": false,
           "full": true,
           "transactions": false,
           "expand": false,
           "owner_funds": false
       }
   ]
}`

**Comment by mounikakun** [comment]
“ledger” if you specified  accounts as true, but are not connected to the server as an admin.
Expected response: `noPermission`
Actual response: No error
Suggested fix: document on clio part for ledger request.

Sample request:
`{
   "method": "ledger",
   "params": [
       {
           "ledger_index": "validated",
           "accounts": true,
           "full": false,
           "transactions": false,
           "expand": false,
           "owner_funds": false
       }
   ]
}`

**Comment by godexsoft** [comment]
@ManiMounikaKunasani please note that clio does not support anything like "being connected as an admin" so instead we decided to return NOT_SUPPORTED error in case the user is attempting to use these parameters ("accounts" and/or "full").

**Comment by mounikakun** [comment]
@godexsoft this issue was raised to fix the documentation part of `ledger` specific to Clio.

**Comment by godexsoft** [comment]
@cjcobb23 please escalate with relevant people in order to get the docs updated :+1:

**Comment by cjcobb23** [comment]
https://github.com/XRPLF/xrpl-dev-portal/issues/1618

**Comment by cindyyan317** [comment]
Close this one since the document of "full" has been updated.
