### ISSUE TITLE
implement amm_info

### ISSUE THREAD

**Issue by cjcobb23** [XRPLF/clio#283]
https://github.com/XRPLF/rippled/pull/4133/files#diff-23668a3cc8b99347f8a0b91c5054ea3a63956e690b2d55b8fc46b392518253f4

**Comment by godexsoft** [comment]
AMM functions were moved into `xrpl_core` [here](https://github.com/XRPLF/rippled/pull/4294). Let's use them and remove the copy-pasted ones when this gets merged to develop in `rippled`.

**Comment by intelliot** [comment]
- Consider the latest changes in amm_info
- Consider any potential implications from https://github.com/XRPLF/rippled/pull/4626

**Comment by intelliot** [comment]
- As part of this issue, please ensure that https://github.com/XRPLF/rippled/pull/4682 is considered and implemented in a matching/compatible manner
