### ISSUE TITLE
Use `#pragma once` instead of include guards

### ISSUE THREAD

**Issue by godexsoft** [XRPLF/clio#286]
Currently we have ifdefs/guards everywhere. 
It's better to use `#pragma once` instead as the compiler caches those and it's generally more efficient than relying on the pre-processor. 
As part of this issue please check whether `#pragma once` is supported on all our target compilers. It's worth noting that as we target **c++20** it's pretty safe to assume that modern major compilers are targeted and they should have support for `#pragma once`.

**Comment by aaryanredd** [comment]
Hello @godexsoft , I am new to Open Source Community. Can I work on this issue? If yes, can you give more details?

**Comment by godexsoft** [comment]
Hi @aaryanredd and thank you for your interest in taking on this issue!
Yes indeed you can work on this if you want to.

Please refer to `CONTRIBUTING.md` for details on how the process works.
I assume you tried to build `clio` already but if not - please read the `README.md` for details on how to get it compiled and running locally.

Now for the task at hand - it should be fairly simple. 
You have to go thru each header file `.h` in `clio` and remove the include guards replacing them with `#pragma once`.
This is the sort of change (Example for `ETLHelpers.h` file):
``` cpp
#ifndef RIPPLE_APP_REPORTING_ETLHELPERS_H_INCLUDED
#define RIPPLE_APP_REPORTING_ETLHELPERS_H_INCLUDED
// lots of code here
#endif  // RIPPLE_APP_REPORTING_ETLHELPERS_H_INCLUDED
```
should become
```cpp
#pragma once
// lots of code here as before
```

Let me know if you need more details :+1:
