### ISSUE TITLE
investigate large partitions in Cassandra

### ISSUE THREAD

**Issue by cjcobb23** [XRPLF/clio#29]
Some of the partitions in our data model are very large. 

The worst offender is the keys table, where there are millions of records in a single partition. For keys, we could do something like have the partition key be the ledger sequence AND the first byte of the key.

The account_tx table also has very large partitions, which correspond to accounts with a lot of transactions. One solution to this would be to have the partition key be the account AND the first `x` bytes of the ledger sequence. In this manner we can split up the records for a given account, so they don't all correspond to the same partition.

This problem could also exist in the objects table, if a ledger object is modified very often over a long period of time. For this, we could do something similar to the solution described above for account_tx.

The other tables don't appear to have this problem.

**Comment by cjcobb23** [comment]
We should also investigate if we should do something like this for Postgres as well

**Comment by godexsoft** [comment]
Will be investigated as part of database research later on. Support for postgres was already implemented and later removed as it wasn't working very well past 1TB db size as well as seemingly no one used anyway.
