### ISSUE TITLE
Check Global Frozen for the offer book in.

### ISSUE THREAD

**Issue by natenichols** [XRPLF/clio#299]
https://github.com/XRPLF/clio/blob/develop/src/rpc/RPCHelpers.cpp/#L1222-L1224

Should be:
```cpp
   bool globalFreeze =
        isGlobalFrozen(backend, ledgerSequence, book.out.account, yield) ||
        isGlobalFrozen(backend, ledgerSequence, book.in.account, yield);
```

**Comment by godexsoft** [comment]
Let's perform this change once we can auto-run integration tests for each PR.

**Comment by cindyyan317** [comment]
Fixed in https://github.com/XRPLF/clio/pull/542
