### ISSUE TITLE
Retrieve NFT offers by account

### ISSUE THREAD

**Issue by tequdev** [XRPLF/clio#314]
It would be nice to have an API to retrieve a list of NFT offers for an account.

If a user forgets the NFT ID that submitted the offer, it is difficult to cancel the offer.

**Comment by ledhed2222** [comment]
hey there - you should be able to do this already with clio or rippled using `account_objects` with the `type` param set to `nft_offer`

**Comment by ledhed2222** [comment]
looks like clio doesn't support the `nft_offer` type param for this API at the moment. re-opening to track that.

**Comment by tequdev** [comment]
Thank you!
