### ISSUE TITLE
Clio not forwarding requests to rippled even after the inclusion of 'ledger_index':'current' in the request.

### ISSUE THREAD

**Issue by mounikakun** [XRPLF/clio#316]
Sampel request:
`{
    "method": "wallet_propose",
    "ledger_index": "current"
}`

Response:
`{"result":{"error":"unknownCmd","error_code":32,"error_message":"Unknown method.","status":"error","type":"response","request":{"method":"server_state","ledger_index":"current","params":[{}]}},"warnings":[{"id":2001,"message":"This is a clio server. clio only serves validated data. If you want to talk to rippled, include 'ledger_index':'current' in your request"}]}`

**Comment by cjcobb23** [comment]
@ManiMounikaKunasani I think this is because `"ledger_index":"current"` needs to be part of the `params` array, like any other parameter. Not passed at the top level of the request.
