### ISSUE TITLE
nft_sell_offers with limit and unassociatedmarker return "internal" error instead of "invalidParams" error.

### ISSUE THREAD

**Issue by mounikakun** [XRPLF/clio#332]
Sample request:
`{
  "method": "nft_sell_offers",
  "params": [{
    "nft_id": "000000004C17E5B8E33245D98126F4A6DF4EA57FF71C027B0000099B00000000",
    "ledger_index": "validated",
    "limit": 10,
    "marker": "10394D3EA937A85A4482D2071412A33C8582A6EB4C3B7FD59C76012D83AC08C6"
  }]
}`

response:
`{
    "result": {
        "error": "internal",
        "error_code": 73,
        "error_message": "Internal error.",
        "status": "error",
        "type": "response",
        "request": {
            "method": "nft_sell_offers",
            "params": [
                {
                    "nft_id": "000000004C17E5B8E33245D98126F4A6DF4EA57FF71C027B0000099B00000000",
                    "ledger_index": "validated",
                    "limit": 10,
                    "marker": "10394D3EA937A85A4482D2071412A33C8582A6EB4C3B7FD59C76012D83AC08C6"
                }
            ]
        }
    },
    "warnings": [
        {
            "id": 2001,
            "message": "This is a clio server. clio only serves validated data. If you want to talk to rippled, include 'ledger_index':'current' in your request"
        }
    ]
}`

Expected:
`{
    "result": {
        "error": "invalidParams",
        "error_code": 31,
        "error_message": "Invalid parameters.",
        "request": {
            "command": "nft_sell_offers",
            "ledger_index": "validated",
            "limit": 10,
            "marker": "10394D3EA937A85A4482D2071412A33C8582A6EB4C3B7FD59C76012D83AC08C6",
            "nft_id": "000000004C17E5B8E33245D98126F4A6DF4EA57FF71C027B0000099B00000000"
        },
        "status": "error"
    }
}`

**Comment by mounikakun** [comment]
Issue exists in "nft_buy_offers" also

**Comment by cjcobb23** [comment]
This should be fixed here, but we should confirm: https://github.com/XRPLF/clio/pull/301
