### ISSUE TITLE
subscribe without parameter response for Clio is different from rippled response.

### ISSUE THREAD

**Issue by mounikakun** [XRPLF/clio#348]
Sample request:
`{
  "id": "Example watch Bitstamp's hot wallet",
  "command": "subscribe"
}`

Rippled response:
`{
  "id": "Example watch Bitstamp's hot wallet",
  "result": {
    
  },
  "status": "success",
  "type": "response"
}`

Clio response:
`{
  "error": "invalidParams",
  "error_code": 31,
  "error_message": "does not contain valid subscription",
  "status": "error",
  "type": "response",
  "id": "Example watch Bitstamp's hot wallet",
  "request": {
    "id": "Example watch Bitstamp's hot wallet",
    "command": "subscribe"
  },
  "warnings": [
    {
      "id": 2001,
      "message": "This is a clio server. clio only serves validated data. If you want to talk to rippled, include 'ledger_index':'current' in your request"
    }
  ]
}`

**Comment by mounikakun** [comment]
Issue exists for unsubscribe also.

**Comment by godexsoft** [comment]
@ManiMounikaKunasani @cjcobb23 

It seems like `rippled` does not error out when no valid subscription channel is specified. 
`clio` however does currently check that at least one of `streams`, `accounts`, `accounts_proposed` or `books` is specified.
Do i understand correctly that we want to just disable this check in `clio`?
