### ISSUE TITLE
For successful transaction of subscribe and unsubscribe, result parameter has extra parameters in Clio response.

### ISSUE THREAD

**Issue by mounikakun** [XRPLF/clio#354]
`"validated": true` 
for subscribe to accounts, accounts_proposed, order books, streams

`"status": "success",
    "validated": true`
for unsubscribe to accounts, accounts_proposed, order books, streams

**Comment by cjcobb23** [comment]
In general, extra fields are not a problem. However, it can't hurt to remove them, and `accounts_proposed` is not returning validated data, so `"validated":true` there is misleading

**Comment by godexsoft** [comment]
This `validated` flag is added globally for all RPCs that return a meaningful JSON object.
To _remove_ it from only those methods means we need to add it to each method that _should_ return this flag.
I'm not sure it's worth the effort. Let me know what you think @cjcobb23 .
