### ISSUE TITLE
Clio is not returning "actNotFound" error for deleted account.

### ISSUE THREAD

**Issue by mounikakun** [XRPLF/clio#374]
Work around:
- Create a new account(or use an existing account).
- Wait till the transaction's Sequence number plus 256 must be less than the current [Ledger Index] to avoid `tecTOO_SOON` error.
- Do an `AccountDelete` transaction.
- verify `account_objects` (which should be returning `"error": "actNotFound"` error)

Sample request with deleted account:
`{
    "method": "account_objects",
    "params": [
        {
            "account": "rrhpB1iso6sFNxhNfTHiFyuAMu5Xrdupmj",
            "deletion_blockers_only": false,
            "limit": 2000,
            "validated": true
        }
    ]
}`

Rippled response:
`{
    "result": {
        "error": "actNotFound",
        "error_code": 19,
        "error_message": "Account not found.",
        "request": {
            "account": "rrhpB1iso6sFNxhNfTHiFyuAMu5Xrdupmj",
            "command": "account_objects",
            "deletion_blockers_only": false,
            "limit": 2000,
            "validated": true
        },
        "status": "error"
    }
}`

Clio response:
`{
    "result": {
        "account": "rrhpB1iso6sFNxhNfTHiFyuAMu5Xrdupmj",
        "account_objects": [],
        "ledger_hash": "D05E845011F985B655D79312C3FC215F8E1FB59210B62882F694010ADA6EAA36",
        "ledger_index": 22929652,
        "validated": true,
        "status": "success"
    },
    "warnings": [
        {
            "id": 2001,
            "message": "This is a clio server. clio only serves validated data. If you want to talk to rippled, include 'ledger_index':'current' in your request"
        }
    ]
}`

FYI: I verified the `complete_ledgers` of Clio `server_info` to make sure the account sequence is in the range.

**Comment by cjcobb23** [comment]
Does this issue exist for `account_info` as well?

**Comment by cjcobb23** [comment]
I think this should be fixed in https://github.com/XRPLF/clio/pull/382, please retest @ManiMounikaKunasani

**Comment by mounikakun** [comment]
Issue is fixed.
