### ISSUE TITLE
Discrepancies in the server_info of Clio on latest develop and last release.

### ISSUE THREAD

**Issue by mounikakun** [XRPLF/clio#401]
Clio on latest develop :
`{
    "result": {
        "info": {
            "complete_ledgers": "23470876-23474648",
            "counters": {
                "rpc": {
                    "server_info": {
                        "started": "8",
                        "finished": "8",
                        "errored": "0",
                        "forwarded": "0",
                        "duration_us": "112249"
                    }
                },
                "subscriptions": {
                    "ledger": 0,
                    "transactions": 0,
                    "transactions_proposed": 0,
                    "manifests": 0,
                    "validations": 0,
                    "account": 0,
                    "accounts_proposed": 0,
                    "books": 0
                }
            },
            "load_factor": 1,
            "clio_version": "0.2.0+0.2.0-13-g8de39739.DEBUG",
            "validated_ledger": {
                "age": 0,
                "hash": "14C194890E86D4778FEE0BB825E57E04FCC50C08F865A6BF2C5EA6E8A681D2A8",
                "seq": 23474648,
                "base_fee_xrp": 1E-5,
                "reserve_base_xrp": 1E1,
                "reserve_inc_xrp": 2E0
            }
        },
        "cache": {
            "size": 4292883,
            "is_full": false,
            "latest_ledger_seq": 23474648
        },
        "etl": {
            "etl_sources": [
                {
                    "validated_range": "23332877-23474648",
                    "is_connected": "1",
                    "ip": "127.0.0.1",
                    "ws_port": "6006",
                    "grpc_port": "50051",
                    "last_msg_age_seconds": "0"
                }
            ],
            "is_writer": true,
            "read_only": false,
            "last_publish_age_seconds": "0"
        },
        "note": "This is a clio server. If you want to talk to rippled, include \"ledger_index\":\"current\" in your request",
        "validated": true,
        "status": "success"
    }
}`

Clio on latest release:
`{
    "result": {
        "info": {
            "complete_ledgers": "21377274-23474658",
            "load_factor": 1,
            "clio_version": "1.0.3-rc1",
            "validation_quorum": 8,
            "rippled_version": "1.10.0-b2",
            "validated_ledger": {
                "age": 0,
                "hash": "3EB93228EFAB2859739CD1508AFC94FED98EAEE7AE2FA3CAF21EE4308C04D412",
                "seq": 23474658,
                "base_fee_xrp": 1E-5,
                "reserve_base_xrp": 1E1,
                "reserve_inc_xrp": 2E0
            },
            "cache": {
                "size": 1336333,
                "is_full": false,
                "latest_ledger_seq": 23474658,
                "object_hit_rate": 1.4911585139998351E-6,
                "successor_hit_rate": 1E0
            }
        },
        "validated": true,
        "status": "success"
    },
    "warnings": [
        {
            "id": 2001,
            "message": "This is a clio server. clio only serves validated data. If you want to talk to rippled, include 'ledger_index':'current' in your request"
        }
    ]
}`

FYI: Clio on latest develop is running on macOS and Clio on latest release is running on Ubuntu.

**Comment by godexsoft** [comment]
I think this was due to running an old version of clio by mistake. I'm closing this, reopen if you find there is still a problem.
