### ISSUE TITLE
Clio API server's warning response message - { id: 2003, message: 'You are about to be rate limited'}

### ISSUE THREAD

**Issue by PaulMoney** [XRPLF/clio#403]
Hello, when I'm sending transactions via Clio API server, I'm always getting _{ id: 2003, message: 'You are about to be rate limited' }_ warning message in a response. The params (CPU, RAM and etc.) of my Clio API server are the same as I'm using in Rippled nodes. However, when I'm making a request directly to the Rippled node (via its public web socket port), I don't have any problems with rate limits.  Maybe somebody had experienced the same problem and could tell me, what I have to verify or change in Clio API server's configuration in order to resolve the rate limit issue. Thanks in advance.

**Comment by godexsoft** [comment]
Hi Paul,

I think you can mitigate the issue by setting up the `dos_guard` section of your configuration file.
You could add your IP to the `whitelist` for example to completely bypass the dos guard for this specific IP.
Alternatively you can set the `max_fetches` (inside `dos_guard`) to some high number (default is 100). This represents the amount of fetches 1 IP can do before it could get rate limited (within one sweep).

Hope this helps.

**Comment by PaulMoney** [comment]
I will try this. Thanks for response !
