### ISSUE TITLE
book_offers without taker_pays returns badMarket error instead of invalidParams.

### ISSUE THREAD

**Issue by mounikakun** [XRPLF/clio#404]
Sample request:
`{
    "method": "book_offers",
    "params": [
        {
            "taker": "r9cZA1mLK5R5Am25ArfXFmqgNwjZgnfk59",
            "taker_gets": {
                "currency": "XRP"
            },
            "limit": 10
        }
    ]
}`

Rippled response:
`{
    "result": {
        "error": "invalidParams",
        "error_code": 31,
        "error_message": "Missing field 'taker_pays'.",
        "request": {
            "command": "book_offers",
            "limit": 10,
            "taker": "r9cZA1mLK5R5Am25ArfXFmqgNwjZgnfk59",
            "taker_gets": {
                "currency": "XRP"
            }
        },
        "status": "error"
    }
}`

Clio response:
`{
    "result": {
        "error": "badMarket",
        "error_code": 42,
        "error_message": "missingTakerPays",
        "status": "error",
        "type": "response",
        "request": {
            "method": "book_offers",
            "params": [
                {
                    "taker": "r9cZA1mLK5R5Am25ArfXFmqgNwjZgnfk59",
                    "taker_gets": {
                        "currency": "XRP"
                    },
                    "limit": 10
                }
            ]
        }
    },
    "warnings": [
        {
            "id": 2001,
            "message": "This is a clio server. clio only serves validated data. If you want to talk to rippled, include 'ledger_index':'current' in your request"
        }
    ]
}`

**Comment by godexsoft** [comment]
This is already fixed in develop. Closing.
