### ISSUE TITLE
Clio web socket responses have extra parameters than rippled.

### ISSUE THREAD

**Issue by mounikakun** [XRPLF/clio#405]
Sample request:
`{"id": 2,"command": "account_info","account": "r4krwypySXzXN8avzGRJCMECUujm3VJsBp","strict": true,"ledger_index": "validated","queue": true}`

Rippled response:
`{"error":"invalidParams","error_code":31,"error_message":"Invalid parameters.","id":2,"ledger_hash":"CDF31686D81F672EF8CEEDDC852661FB1D7175F03EC6C83AE2580036B682B3D6","ledger_index":23502573,"request":{"account":"r4krwypySXzXN8avzGRJCMECUujm3VJsBp","command":"account_info","id":2,"ledger_index":"validated","queue":true,"strict":true},"status":"error","type":"response","validated":true}`

Clio response:
`{"id":2,"result":{"error":"invalidParams","error_code":31,"error_message":"Invalid parameters.","id":2,"ledger_hash":"FF9F73E897AC0BE2E919C9BB91142FBC64B2E8DAD78DB65B1C0C1DDC8233D4F9","ledger_index":23502582,"request":{"account":"r4krwypySXzXN8avzGRJCMECUujm3VJsBp","command":"account_info","id":2,"ledger_index":"validated","queue":true,"strict":true},"status":"error","type":"response","validated":true,"forwarded":true},"status":"success","type":"response","warnings":[{"id":2001,"message":"This is a clio server. clio only serves validated data. If you want to talk to rippled, include 'ledger_index':'current' in your request"}]}`

**Comment by cjcobb23** [comment]
This occurs for requests that are forwarded to rippled
