### ISSUE TITLE
“ledger_entry” with request improperly specified currency code response is missing ledger_hash,ledger_index, validated.

### ISSUE THREAD

**Issue by mounikakun** [XRPLF/clio#406]
Sample request:
`{ "method": "ledger_entry", "params": [{ "ripple_state": { "accounts": [ "rEgAvY1qyEfZxwSaDg5UdLtNQzyvSPEXtV", "rhyxmFfxujVTfxBjug37kouzms6YzWpAUy" ], "currency": "aa" }, "ledger_index": "validated" }] }`

Rippled response:
`{ "result": { "error": "malformedCurrency", "ledger_hash": "AF756E58D568B93B564E8E1A5D9E43CFAAF8C8106F439E0BD893779CC69989DE", "ledger_index": 23530782, "request": { "command": "ledger_entry", "ledger_index": "validated", "ripple_state": { "accounts": [ "rEgAvY1qyEfZxwSaDg5UdLtNQzyvSPEXtV", "rhyxmFfxujVTfxBjug37kouzms6YzWpAUy" ], "currency": "aa" } }, "status": "error", "validated": true } }`

Clio response:
`{ "result": { "error": "malformedCurrency", "error_code": 5000, "error_message": "malformedCurrency", "status": "error", "type": "response", "request": { "method": "ledger_entry", "params": [ { "ripple_state": { "accounts": [ "rEgAvY1qyEfZxwSaDg5UdLtNQzyvSPEXtV", "rhyxmFfxujVTfxBjug37kouzms6YzWpAUy" ], "currency": "aa" }, "ledger_index": "validated" } ] } }, "warnings": [ { "id": 2001, "message": "This is a clio server. clio only serves validated data. If you want to talk to rippled, include 'ledger_index':'current' in your request" } ] }`

**Comment by godexsoft** [comment]
Should be fixed in docs instead: https://github.com/XRPLF/xrpl-dev-portal/issues/1995
