### ISSUE TITLE
Add copyright info to each file

### ISSUE THREAD

**Issue by godexsoft** [XRPLF/clio#411]
We should add and maintain copyright comments similar to what `rippled` does:
```
//------------------------------------------------------------------------------
/*
    This file is part of clio: https://github.com/XRPLF/clio
    Copyright (c) 2022 Ripple Labs Inc.
    Permission to use, copy, modify, and/or distribute this software for any
    purpose  with  or without fee is hereby granted, provided that the above
    copyright notice and this permission notice appear in all copies.
    THE  SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
    WITH  REGARD  TO  THIS  SOFTWARE  INCLUDING  ALL  IMPLIED  WARRANTIES  OF
    MERCHANTABILITY  AND  FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
    ANY  SPECIAL ,  DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
    WHATSOEVER  RESULTING  FROM  LOSS  OF USE, DATA OR PROFITS, WHETHER IN AN
    ACTION  OF  CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
    OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
*/
//==============================================================================
```

**Comment by j0ker70** [comment]
Hello. Sorry for asking but I am trying to contribute to my first open source project. Can you be more specific to which files should I actually add the copyright files? I have checked the `rippled` project. As it seems, in that project not all files have copyright statements included.

**Comment by godexsoft** [comment]
Hi @j0ker70,
Only `.h` and `.cpp` source files should have this copyright at the top. 
If in `rippled` they missed this in some files it's probably a mistake.
If you would like to contribute to `clio` as your first opensource project - you are very welcome to take this issue or any other issue with `good first issue` label on it.

**Comment by j0ker70** [comment]
Thanks for replying @godexsoft. I am a little stuck now. As told in `CONTRIBUTING.md`, I have completed these commands.

```
# Create a backup of your branch
git branch <your feature branch>_bk

# Rebase and squash commits into one
git checkout develop
git pull origin develop
git checkout <your feature branch>
git rebase -i develop
```

But after that changes are made in the feature-branch, not in develop branch. Please, can you tell me how can I push my changes?

**Comment by j0ker70** [comment]
I have merged my feature branch onto the develop branch in the end. Here is the pull request [link](https://github.com/XRPLF/clio/pull/412).

**Comment by godexsoft** [comment]
> I have merged my feature branch onto the develop branch in the end. Here is the pull request [link](https://github.com/XRPLF/clio/pull/412).

Hi @j0ker70 , thanks for your PR - It looks good :+1: 
I'm just waiting to confirm with legal that the copyright message is indeed correct. If it's not then i'll have to ask you to find-replace a few things and if it is correct then i'll merge your changes in the coming days :bow:

**Comment by godexsoft** [comment]
Hi @j0ker70, fyi we are still waiting for legal to confirm what the copyright message should be. Will keep you posted.

**Comment by godexsoft** [comment]
Hi @j0ker70 , let's update it with this:

```
//------------------------------------------------------------------------------
/*
    This file is part of clio: https://github.com/XRPLF/clio
    Copyright (c) 2022, the clio developers.

    Permission to use, copy, modify, and distribute this software for any 
    purpose with or without fee is hereby granted, provided that the above 
    copyright notice and this permission notice appear in all copies.

    THE  SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
    WITH  REGARD  TO  THIS  SOFTWARE  INCLUDING  ALL  IMPLIED  WARRANTIES  OF
    MERCHANTABILITY  AND  FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
    ANY  SPECIAL,  DIRECT,  INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
    WHATSOEVER  RESULTING  FROM  LOSS  OF USE, DATA OR PROFITS, WHETHER IN AN
    ACTION  OF  CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
    OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
*/
//==============================================================================
```

Once it's updated i'll merge it into `develop`. 
Thanks!
