### ISSUE TITLE
Secure communication with Clio API server

### ISSUE THREAD

**Issue by PaulMoney** [XRPLF/clio#420]
Hello,

Does Clio API server have an opportunity to configure secure communication via **wss** on port 51233 ? If yes, what additional configurations should be applied to the config file ? 

And the second question is related to the _etl_sources_ configuration. As I understand, Clio API server can connect to the rippled node only via public unsecured web socket (ws) port ?

**Comment by godexsoft** [comment]
Hi @PaulMoney,

As far as i know you can make `clio` create a `wss` server by configuring `ssl_cert_file` and `ssl_key_file` in `clio`'s config.

And `clio` certainly can use both `ws` and `wss` when talking to `rippled` (etl_sources). In fact `clio` automatically detects which connection is available/configured on the `rippled` server being accessed. There is nothing you need to configure in `clio`'s config file to support `rippled` over `wss`.

@cjcobb23 correct me if i'm wrong please.
Let me know if you run into problems configuring `wss`.

**Comment by PaulMoney** [comment]
Hi @godexsoft 

Where should I place `ssl_cert_file` and `ssl_key_file` in `clio`'s config ? Under `server` object or in some other place ? 

And the second question is related to **file permission**. As my key and the certificate are in root protected folders (i.e. `/etc/ssl/private/server.key`, `/etc/ssl/certs/server.crt`), do I need to change the ownership these folders to `clio` user ?

**Comment by godexsoft** [comment]
> Where should I place `ssl_cert_file` and `ssl_key_file` in `clio`'s config ? Under `server` object or in some other place ?

If i read the code correctly, those two are specified in the top level JSON of the configuration file like so:
```
{
    "server":{
        "ip": "0.0.0.0",
        "port": 51233
    },
    "ssl_cert_file" : "/full/path/to/cert.file",
    "ssl_key_file" : "/full/path/to/key.file"
}
```
This is actually a bit surprising. I would expect them to be part of the `server` configuration object too. This may change in the future.

> And the second question is related to **file permission**. As my key and the certificate are in root protected folders (i.e. `/etc/ssl/private/server.key`, `/etc/ssl/certs/server.crt`), do I need to change the ownership these folders to `clio` user ?

It's up to you how you do this. You can copy the two files as `root` somewhere accessible by the user you run `clio` from and then `sudo chown` them to your user. You can directly change their permissions so it's readable by your user. Or you can even run `clio` as root - but this is strongly discouraged.

Hope this helps :+1:

**Comment by PaulMoney** [comment]
`"ssl_cert_file", "ssl_key_file" :`  worked perfectly. Thanks for help and the response.

**Comment by godexsoft** [comment]
> `"ssl_cert_file", "ssl_key_file" :`  worked perfectly. Thanks for help and the response.

Awesome. Glad it worked out. We will update the example config and docs to cover these parameters.
Thanks for flagging it 👍
