### ISSUE TITLE
Clio API server does not download full ledger history

### ISSUE THREAD

**Issue by PaulMoney** [XRPLF/clio#425]
Hello,

Recently, I have configured **a new Clio API server instance** and connected it to my locally running **rippled full-history node**. As I understood from the documentation a new Clio API server instance should automatically start downloading all available ledger data from the connected full-history node. However, when I logged in to the Cassandra DB and selected ledger range, it showed that Clio API server started extracting data only from the latest available ledger at the data source (at the connection time it was 258637).

```
hero@vm-clio1-dev-westeu-001:~$ cqlsh
Connected to Clio Cluster at 127.0.0.1:9042
[cqlsh 6.1.0 | Cassandra 4.1 | CQL spec 3.4.6 | Native protocol v5]
Use HELP for help.
cqlsh> SELECT * FROM clio.ledger_range;

 is_latest | sequence
-----------+----------
     False |   258637
      True |   259163
```

Also, I verified the `journalctl `logs to be sure, that my Clio API server has connected to the appropriate node (has full-ledger available). Here is a connection `log `from the `journalctl`:

`Nov 24 14:42:12 vm-clio1-dev-westeu-001 clio_server[17927]: [2022-11-24 14:42:12.640532] [0x00007f26ee7fc700] [debug] execute : Attempting to execute func. ledger sequence = 259153 - source = { validated_ledger : 3-259163 , ip : 172.29.0.6 , web socket port : 6005, grpc port : 50051 }`

So, the question is, maybe I have missed something and should add to my Clio config file ? Or selecting ledger range is not an appropriate way to verify that all ledger data has been successfully extracted  ?

**Comment by godexsoft** [comment]
Hi @PaulMoney,

Thanks for pointing out that this behaviour is not well documented (#250).

The way it works is this:
- If `start_sequence` (ledger index, integer value) is specified in the top-level of the JSON config then `clio` will start by fetching the specified ledger index
- If no `start_sequence` is specified `clio` will fetch wait for a ledger (current rippled one) to validate and start from the just validated ledger index
- There is currently no backfilling in `clio` (#66) meaning that `clio` will never learn about any ledger older than `start_sequence` (or latest ledger available at first start of `clio`)

So I think what you want to do is specify `start_sequence` to some ledger index that you would like to start with. Drop the `clio` keyspace. Start `clio` and if your `rippled` already got full history then `clio` should start filling data pretty much instantly.

Let me know if this works for you and/or if you will need any more support.
Once again, thanks for pointing out the docs are missing information about this. We will document all this soon.

**Comment by PaulMoney** [comment]
Thank you for your response. Your suggestion worked perfectly for me.

**Comment by godexsoft** [comment]
Glad to hear it helped! We will improve the documentation soon. Cheers
