### ISSUE TITLE
Introduce the same fixes to gateway_balances as in rippled

### ISSUE THREAD

**Issue by godexsoft** [XRPLF/clio#464]
See  https://github.com/XRPLF/rippled/pull/4355
We need to make sure we are on the same page with their implementation.

**Comment by cindyyan317** [comment]
Clio has the overflow issue as well. 
https://github.com/XRPLF/clio/blob/develop/src/rpc/handlers/GatewayBalances.cpp#L154

How to reproduce:
`
{
    "method": "gateway_balances",
    "params": [
        {
           "account": "raiata7DoTJL5CMHuYC8BYGE6J4psyCMcE"
        }
    ]}
`
