### ISSUE TITLE
support for secure_gateway

### ISSUE THREAD

**Issue by natenichols** [XRPLF/clio#48]
I'm fairly sure we have something similar w/ `whitelist`, but we should explicitly support this.

**Comment by cjcobb23** [comment]
rippled actually allows ips in `secure_gateway` to pass a different ip in the header, which then rippled uses for rate limiting. The use case is something like xrplcluster.com redirects to s2, and s2 needs to rate limit not xrplcluster.com, but the original client that connected to xrplcluster.com

**Comment by cjcobb23** [comment]
I think the software should just accept a field in any request called `client_ip`, and if the request is coming from an ip on the whitelist (list of ips specified in the config), charge the specified ip. Otherwise, ignore it.

**Comment by WietseWind** [comment]
... Isn't this covered by:

```
    "dos_guard":
    {
        "whitelist":["127.0.0.1"]
    },
```

.... then to offload rate limiting to a reverse proxy?

**Comment by cjcobb23** [comment]
> Isn't that what the `dos_guard` (whitelist) + rate limiting on the reverse proxy could do?
> 
> ```
>     "dos_guard":
>     {
>         "whitelist":["127.0.0.1"]
>     },
> ```
> 
> .... then to offload rate limiting to a reverse proxy?

Mostly. There's just the part where rippled allows an IP listed as a secure gateway to pass a different ip in the header, and rippled rate limits that ip instead. Clio doesn't support the header part.

**Comment by WietseWind** [comment]
With resource based 'billing' not mattering as much when things are served from a backend where things should be stored efficiently and pre-computed, I think it makes sense to leave rate limiting fully up to a reverse proxy: that would also allow for much more fine grained rate limiting. Keeping Clio simple/light indeed.

**Comment by godexsoft** [comment]
Looks like the general agreement here is not to implement it. Closing for now - reopen if needed.
