### ISSUE TITLE
Parallel Load

### ISSUE THREAD

**Issue by natenichols** [XRPLF/clio#49]
Reporting mode has a tool for loading SHAMap into cassandra, but clio has to manually load all data into its native data format. 

We should add functionality that allows for multiple write nodes to load data into the same database. I.E.

node 1 loads ledgers 32,000 to 20,000,000
node 2 loads ledgers 20,000,001 to 40,000,000
node 3 loads ledgers 40,000,001 to 60,000,000
node 4 loads ledgers 60,000,000 to present

**Comment by kuznetsss** [comment]
It would be better to create a service with dumps of database instead. This is what the community actually wants.
