### ISSUE TITLE
Redesign proxy architecture

### ISSUE THREAD

**Issue by cjcobb23** [XRPLF/clio#51]
The proxy architecture is very simply, but may not be the best design. The way it works now is if a request needs to be proxied (either is one of the requests that is always proxied, like `submit`, or specifies `ledger_index:current`), clio picks an etl source at random and forwards the request there. This works, but there are a number of improvements that could be made.

1. Consider disabling proxy for certain requests. For instance, `ledger_data` probably should never be proxied. The call is iterative, and iterating the whole ledger takes minutes, during which time the open ledger changes many times over. The list of RPCs that actually need access to the open ledger is quite small, so we could probably disable proxying on quite a bit.
2. Think about how to provide a consistent view to the open ledger. clio uses a collection of etl sources, and each of those has a different view of the open ledger. Transaction propagation results in a sort of eventual consistency, though there is no guarantee on consistency prior to consensus, at which point the data is validated and clio writes it to the database. When we pick a random p2p node to proxy a request to, subsequent requests are likely to go to a different p2p node. So if a user calls `server_info` and uses the `load_factor` to calculate fees, and then calls `submit` to submit the transaction, `submit` will probably go to a different p2p node than `server_info` did, which could cause incorrect fee calculation. A similar situation can occur with `account_info`. 
3. Have clio be smarter about which node to proxy to. clio could track the load factor of each p2p node, and forward requests to the node with the lowest load factor, or some other measure of idleness. At a certain point, clio should reject proxy requests if the p2p nodes are in danger of going out of sync.
4. Consider caching data in clio. We proxy `server_info` to get the load factor, but we could probably just query each p2p node once per second to get their load factor, and then cache that in clio. We might be able to do something like this for `account_info` as well.
5. Enable separating ETL sources and proxy endpoints. Proxy endpoints could get bombarded with traffic and go out of sync, and then can no longer be ETL sources, and the database will stop getting updates.
6. Make the proxy asynchronous, so we are not sitting on a thread until the response comes back.

Lastly, what we really need is some way to handle a lot of requests that require a p2p node without causing the nodes to desync. Reporting nodes simply slow down when there are too many requests, forcing requests to wait in a queue and eventually returning an error `rpcTOO_BUSY`. p2p nodes on the other hand lose sync, at which point they can't handle any requests until they resync, which can take several seconds or longer.

**Comment by natenichols** [comment]
A couple preliminary thoughts
1) We should consider disabling `ledger_index: 'validated' | 'current' | 'closed'` for any RPC that requires pagination. It doesn't make a lot of sense to allow this behavior (w/ the exception of book offers) because the validated/closed/open ledger can change at any time, and give clients invalid responses

2/3/4) These seem to fall into the category of smarter load balancing.

4) I don't have any opinions here. Seems like a reasonable suggestion. For `account_info`, we should try to make load balancing smarter such that the same clients (when requesting the open ledger + submitting) will attempt to hit the same p2p node for a consistent view of the open ledger.

5) 👍 

6) 👍

**Comment by godexsoft** [comment]
Other than than the above comments, consider this:
1. Specifying ETL source in config with `localhost` and the port being the same one `clio` listens on (51233) will produce a loop of death if we try to do the `server_info` or any other forwarding command.
2. The `server_info` command will request the `server_info` from `rippled` using a random ETLSource meaning the response is potentially not consistent as technically the version of `rippled` on each source may be different entirely.
