### ISSUE TITLE
New API

### ISSUE THREAD

**Issue by cjcobb23** [XRPLF/clio#55]
Design a new and more consistent API

**Comment by cjcobb23** [comment]
Just to be clear, right now clio is targeting the rippled API. The rippled API has numerous issues though, mainly consistency. See here for discussion: https://github.com/ripple/rippled/issues/2599

**Comment by godexsoft** [comment]
Does not look to me like this will ever happen. wdyt @cjcobb23?
Closing for now.

**Comment by cjcobb23** [comment]
This is currently being designed by @mduo13

**Comment by godexsoft** [comment]
Ok. Does it mean we will have a new API for both clio and rippled or we will actually somehow diverge our APIs? Anyway, let me reopen.

**Comment by godexsoft** [comment]
There is a big developer cost from client/user perspective to use two different sets of APIs or transition from old one to the new one.
If we actually ever get to finish the design and decide to implement it, we will open new issues for its adoption in `clio`.
