### ISSUE TITLE
Enhance logging

### ISSUE THREAD

**Issue by cjcobb23** [XRPLF/clio#57]
We should audit the logs and make sure everything that's being logged makes sense, and everything that makes sense is being logged, at the appropriate levels.
We should make some progress on this before the beta, mainly so we have good logs to debug things.

**Comment by cjcobb23** [comment]
For the beta, we need good logging around how long things take. We want to be able to easily determine what exactly is slow (or fast). We should log the time of every database fetch, every RPC call overall, and every serialization to JSON.

**Comment by cjcobb23** [comment]
For version 1.0, we need to focus on logging for usability. We need descriptive error messages for when things are going wrong. Some things that come to mind are issues connecting to rippled (rate limiting, ledger not found, can't connect, etc), or issues connecting to the database. We should say the error, and also what to do about it. It should be very clear when the software is working correctly, and very clear when it is not.

**Comment by godexsoft** [comment]
Logging has been somewhat improved over the last releases of `clio`. It's an endless job, so there is no point to have this issue here. Closing.
