### ISSUE TITLE
Don't use rippled JSON

### ISSUE THREAD

**Issue by cjcobb23** [XRPLF/clio#58]
We use rippled JSON to serialize ledger objects and transactions to JSON. It's not used when users specify the binary flag. We should rewrite the rippled serialization to JSON code in clio and use boost JSON.

**Comment by cjcobb23** [comment]
JSON serialization is actually quite slow. It can take tens of milliseconds to serialize 200 offers to JSON. We should see if Boost JSON speeds this up. If it doesn't, maybe we need to look into some sort of parallel deserializer, and possibly even cache deserialized JSON for a short time.

**Comment by godexsoft** [comment]
Is this still a thing @cjcobb23 ? i think we are using boost.json everywhere we can atm.?
I'm closing this for now. Reopen if you think this issue still stands.

**Comment by cjcobb23** [comment]
No this is not done, we are still converting from binary to rippled JSON then to boost JSON

**Comment by godexsoft** [comment]
Ok, let's reopen then.

**Comment by godexsoft** [comment]
It might be easier for us to adopt `rippled` JSON library than to do it the other way around.
We will talk to `rippled` engineers about this in the future and decide together.

**Comment by kuznetsss** [comment]
Decided to not do this since we will have to implement the same logic in Clio. It's better to use existing library.
