### ISSUE TITLE
Querying the open ledger

### ISSUE THREAD

**Issue by cjcobb23** [XRPLF/clio#59]
We should look into storing the open ledger in Redis, or something similar.

Or maybe each clio server can keep it's own cache.

**Comment by cjcobb23** [comment]
It's not clear if this is needed. We need to go through the use cases and see when the open ledger is actually needed.

**Comment by godexsoft** [comment]
We have proxying for this. We only receive validated/closed ledgers so seems like proxying is the solution as `clio` was not really meant to be used on live data. Closing.
