### ISSUE TITLE
gateway_balances with existent account but not in the ripple state of required account returns error.

### ISSUE THREAD

**Issue by mounikakun** [XRPLF/clio#624]
Sample request:
`{
    "method": "gateway_balances",
    "params": [
        {
            "account": "rpxnjVyvHASnfjYPnyS8uaEakd4niBLdxZ",
            "hotwallet": "rGtwpwR21KXzWob8Ne2975FWLwPNJHhV8",
            "ledger_index": "validated",
            "strict": true
        }
    ]
}`

Clio response:
`{
    "result": {
        "error": "invalidParams",
        "error_code": 31,
        "error_message": "invalidHotWallet",
        "status": "error",
        "type": "response",
        "request": {
            "method": "gateway_balances",
            "params": [
                {
                    "account": "rpxnjVyvHASnfjYPnyS8uaEakd4niBLdxZ",
                    "hotwallet": "rGtwpwR21KXzWob8Ne2975FWLwPNJHhV8",
                    "ledger_index": "validated",
                    "strict": true
                }
            ]
        }
    },
    "warnings": [
        {
            "id": 2001,
            "message": "This is a clio server. clio only serves validated data. If you want to talk to rippled, include 'ledger_index':'current' in your request"
        }
    ]
}`

Rippled response:
`{
    "result": {
        "account": "rpxnjVyvHASnfjYPnyS8uaEakd4niBLdxZ",
        "ledger_hash": "3F0780BDA03E501CEB9AAC277024F337D5A5AEE1BCD3DDD878F670AF554BA04B",
        "ledger_index": 28132342,
        "status": "success",
        "validated": true
    }
}`

**Comment by cindyyan317** [comment]
According to doc https://xrpl.org/gateway_balances.html#possible-errors, clio's behavior is correct.
