### ISSUE TITLE
Fix default limit value mismatch 

### ISSUE THREAD

**Issue by cindyyan317** [XRPLF/clio#648]

**Comment by mounikakun** [comment]
`account_tx` default limit still needs to be fixed.

**Comment by cindyyan317** [comment]
> `account_tx` default limit still needs to be fixed.

Rippled does not have the default limit for account_tx. @mounikakun can you please open another issue to track this?

**Comment by ckniffen** [comment]
This was also reported here. https://github.com/XRPLF/xrpl.js/issues/2354.  An old clientlib defaulted this to 400 so this fix will still be a problem for default values.
