### ISSUE TITLE
Ledger with owner_funds true returns notSupported error.

### ISSUE THREAD

**Issue by mounikakun** [XRPLF/clio#650]
request:
`{
    "method": "ledger",
    "params": [{
        "ledger_hash": "F3A84C1C0FCFC25FDA3251E2886F36AC1E6AD80AC68E9C4EDEB0EEA5915FB0E1",
        "transactions": true,
        "expand": true,
        "owner_funds": true
    }]
}`

Response:
`{
    "result": {
        "error": "notSupported",
        "error_code": 75,
        "error_message": "Not supported field 'owner_funds's value 'true'",
        "status": "error",
        "type": "response",
        "request": {
            "method": "ledger",
            "params": [
                {
                    "ledger_hash": "F3A84C1C0FCFC25FDA3251E2886F36AC1E6AD80AC68E9C4EDEB0EEA5915FB0E1",
                    "transactions": true,
                    "expand": true,
                    "owner_funds": true
                }
            ]
        }
    },
    "warnings": [
        {
            "id": 2001,
            "message": "This is a clio server. clio only serves validated data. If you want to talk to rippled, include 'ledger_index':'current' in your request"
        }
    ]
}`

**Comment by cindyyan317** [comment]
"queue" is another unsupported field but not stated on doc https://xrpl.org/ledger-clio.html#ledger

**Comment by cindyyan317** [comment]
owner_funds can be implemented in clio. We will do it.

**Comment by cindyyan317** [comment]
Fixed
