### ISSUE TITLE
gateway_balances with malformed hotwallet account returns invalidParams response

### ISSUE THREAD

**Issue by mounikakun** [XRPLF/clio#653]
As per [documentation](https://xrpl.org/gateway_balances.html#gateway_balances) there's no `actMalformed` error but for all malformed accounts Clio returns `actMalformed` error.

Request:
`{
    "method": "gateway_balances",
    "params": [
        {
            "account": "rPMeLRzDEBb2S8kSwynm1if6j6N58xQtv7",
            "hotwallet": [
                "rhKKk5KB8LuxmjvTSA7r3iYmJXGqnno7M"
            ],
            "ledger_index": "validated",
            "strict": true
        }
    ]
}`

Response:
`{
    "result": {
        "error": "invalidParams",
        "error_code": 31,
        "error_message": "hotwalletMalformed",
        "status": "error",
        "type": "response",
        "request": {
            "method": "gateway_balances",
            "params": [
                {
                    "account": "rPMeLRzDEBb2S8kSwynm1if6j6N58xQtv7",
                    "hotwallet": [
                        "rhKKk5KB8LuxmjvTSA7r3iYmJXGqnno7M"
                    ],
                    "ledger_index": "validated",
                    "strict": true
                }
            ]
        }
    },
    "warnings": [
        {
            "id": 2001,
            "message": "This is a clio server. clio only serves validated data. If you want to talk to rippled, include 'ledger_index':'current' in your request"
        }
    ]
}`

**Comment by mounikakun** [comment]
During the discussion, it was decided to raise to issue as Clio do not return `actMalformed ` error but according to documentation there is no need to do that.

**Comment by cindyyan317** [comment]
Discussed with Mounika offline, we decide to keep this as it is for now.
