### ISSUE TITLE
gateway_balances with unassociated hotwallet account returns invalidParams error

### ISSUE THREAD

**Issue by mounikakun** [XRPLF/clio#654]
As per documentation, clio should return invalidHotWallet error for the addresses specified in the hotwallet field is not the address of an account holding currency issued by the account from the request but there's  invalidParams error.

Request:
`{
    "method": "gateway_balances",
    "params": [
        {
            "account": "rPMeLRzDEBb2S8kSwynm1if6j6N58xQtv7",
            "hotwallet": [
                "rH9pnDCtgAbFjozbZQuJWvPM8QHweXgZhj"
            ],
            "ledger_index": "validated",
            "strict": true
        }
    ]
}`

Response:
`{
    "result": {
        "error": "invalidParams",
        "error_code": 31,
        "error_message": "invalidHotWallet",
        "status": "error",
        "type": "response",
        "request": {
            "method": "gateway_balances",
            "params": [
                {
                    "account": "rPMeLRzDEBb2S8kSwynm1if6j6N58xQtv7",
                    "hotwallet": [
                        "rH9pnDCtgAbFjozbZQuJWvPM8QHweXgZhj"
                    ],
                    "ledger_index": "validated",
                    "strict": true
                }
            ]
        }
    },
    "warnings": [
        {
            "id": 2001,
            "message": "This is a clio server. clio only serves validated data. If you want to talk to rippled, include 'ledger_index':'current' in your request"
        }
    ]
}`

**Comment by cindyyan317** [comment]
@mounikakun Please verify on the latest develop branch

**Comment by mounikakun** [comment]
@cindyyan317 this issue is fixed but gateway_balances with non existent hotwallet account also returns `invalidHotWallet ` which used to be `invalidParams `. For all other cases with any non existent account returns `*NotFound ` so what should the appropriate error for gateway_balances with non existent hotwallet account ?

**Comment by cindyyan317** [comment]
> @cindyyan317 this issue is fixed but gateway_balances with non existent hotwallet account also returns `invalidHotWallet ` which used to be `invalidParams `. For all other cases with any non existent account returns `*NotFound ` so what should the appropriate error for gateway_balances with non existent hotwallet account ?

yes. we don't check each account of hot wallets from db, because it is slow. The hot wallets can be a lot . It is okay to return invalidHotWallet.
