### ISSUE TITLE
[ledger_data] with limit zero do not return error.

### ISSUE THREAD

**Issue by mounikakun** [XRPLF/clio#658]
Request:
`{
    "method": "ledger_data",
    "params": [
        {
            "limit": 0
        }
    ]
}`

Response:
`{
    "result": {
        "ledger_hash": "87489EE37857934503A2F8AF818A997085155B9EA3577BFA79024827E2AD65A0",
        "ledger_index": 29087459,
        "validated": true,
        "state": [],
        "ledger": {
            "accepted": true,
            "account_hash": "15909695004C9E8F1B5737C651E6A1DD4233DFEEC87828B83AD522E4BD0A3A19",
            "close_flags": 0,
            "close_time": 738867012,
            "close_time_human": "2023-May-31 16:50:12.000000000 UTC",
            "close_time_resolution": 10,
            "hash": "87489EE37857934503A2F8AF818A997085155B9EA3577BFA79024827E2AD65A0",
            "ledger_hash": "87489EE37857934503A2F8AF818A997085155B9EA3577BFA79024827E2AD65A0",
            "ledger_index": "29087459",
            "parent_close_time": 738867011,
            "parent_hash": "282F4382B8D77F287003F57518F184FBB02AF7C222D321617B3BBFEE46E74715",
            "seqNum": "29087459",
            "totalCoins": "99987016335039830",
            "total_coins": "99987016335039830",
            "transaction_hash": "0000000000000000000000000000000000000000000000000000000000000000",
            "closed": true
        },
        "status": "success"
    },
    "warnings": [
        {
            "id": 2001,
            "message": "This is a clio server. clio only serves validated data. If you want to talk to rippled, include 'ledger_index':'current' in your request"
        }
    ]
}`

Expected:
`invalidParams` error

**Comment by godexsoft** [comment]
This is no longer needed. We are going to do exactly as rippled does for this limit field. Rippled returns empty state array for limit 0 and clio does the same.
