### ISSUE TITLE
[ledger_data] do not follow limit values as per documentation

### ISSUE THREAD

**Issue by mounikakun** [XRPLF/clio#659]
test_ledger_data_with_binary_true_and_limit_greater_than_2048
`{
    "method": "ledger_data",
    "params": [
        {
            "limit": 2050,
            "binary": true
        }
    ]
}`

Response:
No error

test_ledger_data_with_binary_false_and_limit_greater_than_256
`{
    "method": "ledger_data",
    "params": [
        {
            "limit": 260
        }
    ]
}`

Response:
No error

**Comment by cindyyan317** [comment]
The max limit for ledger_data is not the same value depends on binary value. So ledger_data auto adjust the value inside.

**Comment by godexsoft** [comment]
We decided to change the behaviour and mimic rippled more closely for the `limit` field. 
This now means that the issue described here is no longer an issue because clio now does exactly what rippled does in this case.
