### ISSUE TITLE
noripple_check with malformed account response is missing some parameters.

### ISSUE THREAD

**Issue by mounikakun** [XRPLF/clio#660]
Request:
`{
    "method": "noripple_check",
    "params": [
        {
            "account": "r7x8JFCExiWopq7YuhK8AXjLhZe4fQ5e",
            "ledger_index":"validated",
            "role": "gateway",
            "transactions": true
        }
    ]
}`

Clio response:
`{
    "result": {
        "error": "actMalformed",
        "error_code": 35,
        "error_message": "accountMalformed",
        "status": "error",
        "type": "response",
        "request": {
            "method": "noripple_check",
            "params": [
                {
                    "account": "r7x8JFCExiWopq7YuhK8AXjLhZe4fQ5e",
                    "ledger_index": "validated",
                    "role": "gateway",
                    "transactions": true
                }
            ]
        }
    },
    "warnings": [
        {
            "id": 2001,
            "message": "This is a clio server. clio only serves validated data. If you want to talk to rippled, include 'ledger_index':'current' in your request"
        }
    ]
}`

Rippled response:
`{
    "result": {
        "error": "actMalformed",
        "error_code": 35,
        "error_message": "Account malformed.",
        "ledger_hash": "AEEF7A04B2F0448307CD4F94877CB326A86C56838ED42E67CC15F6F74B578453",
        "ledger_index": 29089522,
        "request": {
            "account": "r7x8JFCExiWopq7YuhK8AXjLhZe4fQ5e",
            "command": "noripple_check",
            "ledger_index": "validated",
            "role": "gateway",
            "transactions": true
        },
        "status": "error",
        "transactions": [],
        "validated": true
    }
}`

**Comment by godexsoft** [comment]
We should update the doc instead stating that "Error responses may optionally include `ledger_index` and `ledger_hash`". Empty list of transactions looks like a bug in `rippled` and probably should be removed from error response.

**Comment by godexsoft** [comment]
@mounikakun, meanwhile please ignore those extra response fields for this RPC in integration tests.

**Comment by godexsoft** [comment]
Removal of `transactions` from error responses in rippled: https://github.com/XRPLF/rippled/issues/4616
