### ISSUE TITLE
Clio API server health endpoint

### ISSUE THREAD

**Issue by PaulMoney** [XRPLF/clio#704]
I'm wondering if the Clio API server has a **health** endpoint to check whether the Clio API server is running and accepting API requests, similar to the "/health" endpoint on port 51235 in rippled, which indicates if the node is running and synchronised with the rest of the network. Or this is done only in the code, by trying to connect to Clio node ?

**Comment by godexsoft** [comment]
Hi @PaulMoney, Clio supports `server_info` that can give you some insights on how the server is performing when queried from `localhost` (for example via some scripts running on the same machine). Other than that there is no health endpoint at this moment.

**Comment by PaulMoney** [comment]
@godexsoft Thanks for response.

**Comment by intelliot** [comment]
Here is the [documentation of server_info (Clio)](https://xrpl.org/server_info-clio.html)
