### ISSUE TITLE
Clio ETL Crash Upon Amendment Enablement (ie. XrpFees)

### ISSUE THREAD

**Issue by injaelee** [XRPLF/clio#709]
# Root Issue
- `protobuf` definition mismatch

# Symptom
Upon enabling the `XRPFees` amendment, there is a new attribute in one of the data models defined in the protobuf definition file. Clio using the older version of the `rippled` as a library is not able to recognize / unmarshall the data causing a crash.

# Path Forward
- Migrate Clio to the Conan build system 
  - Enables Clio to build the latest `rippled` as a library

**Comment by godexsoft** [comment]
Reason of crash is in #364.
This crash is also fixed by #706. Conan part is being worked on.
