### ISSUE TITLE
[WS] Unsubscribe Request With and Without `ledger_index`

### ISSUE THREAD

**Issue by injaelee** [XRPLF/clio#721]
# Observed Behavior
Making an unsubscribe request to Clio returns `"error": "malformedStream"` without `"ledge_index": "current"`

With `"ledge_index": "current"`, the call succeed.
```json
{
    "accounts": [
        "rrpNnNLKrartuEqfJGpqyDwPj1AFPg9vn1"
    ],
    "accounts_proposed": [
        "rrpNnNLKrartuEqfJGpqyDwPj1AFPg9vn1"
    ],
    "books": [
        {
            "both": true,
            "taker_gets": {
                "currency": "USD",
                "issuer": "rUQTpMqAF5jhykj4FExVeXakrZpiKF6cQV"
            },
            "taker_pays": {
                "currency": "XRP"
            }
        }
    ],
    "command": "unsubscribe",
    "id": 1,
    "streams": [
        "ledger",
        "server",
        "transactions",
        "transactions_proposed"
    ]
}
```

# Expected Behavior
The unsubscribe call should succeed regardless of the `ledger_index` parameter.

**Comment by cindyyan317** [comment]
Regarding the error,  @injaelee  Clio server has not supported the "server" stream, So it returns this error.  

BTW ,We should reject the subscribe / unsubscribe request when "ledger_index" is "current". Subscribe request needs a live long connection, forwarding such request to rippled will create connection between rippled and clio, not with user. This is the known issue. @godexsoft

**Comment by cindyyan317** [comment]
Keep this issue open until we reach a decision if we will implement "server" or not.

**Comment by cindyyan317** [comment]
Close this one , since we decide not to implement "server" stream in Clio
