### ISSUE TITLE
The github release notes are missing for 1.1.0

### ISSUE THREAD

**Issue by ckniffen** [XRPLF/clio#794]
https://github.com/XRPLF/clio/releases is missing several releases and RELEASENOTES.md is way out of date.

Reported in Discord by KipDawgz.

**Comment by godexsoft** [comment]
Thanks for reporting this!

1) There is no such thing as Clio 1.1.0 - it will be 2.0 instead
2) RELEASENOTES.md will be updated, thanks

**Comment by godexsoft** [comment]
Will request doc update for https://xrpl.org/nft_info.html to remove mention of 1.1.0

**Comment by godexsoft** [comment]
https://github.com/XRPLF/xrpl-dev-portal/issues/2066

**Comment by godexsoft** [comment]
Closing this now. This should eventually get resolved on the docs portal. 
Issue to track: https://github.com/XRPLF/xrpl-dev-portal/issues/2066

As for the RELEASENOTES.md they will be updated with the upcoming release 2.0.
