### ISSUE TITLE
APIv2(account_info): handle invalid "signer_lists" value

### ISSUE THREAD

**Issue by intelliot** [XRPLF/clio#798]
https://github.com/XRPLF/rippled/pull/4585

**Comment by cindyyan317** [comment]
No change needed for clio.
For "signer_lists" , clio raises error for non-boolean input.  https://github.com/XRPLF/clio/blob/d61d702ccd761ea5a5b37f3341359b2c42e93285/src/rpc/handlers/AccountInfo.h#L93C14-L93C29
