### ISSUE TITLE
deposit_authorized for accounts without authorization results in true

### ISSUE THREAD

**Issue by mounikakun** [XRPLF/clio#811]
Steps:
- generate two new accounts
- request deposit_authorized with accounts one as source account and the other as destination account

Expected:
`'deposit_authorized': False` in the response

Actual:
`'deposit_authorized': True`

**Comment by mounikakun** [comment]
For` 'deposit_authorized': True` the source account should be deposit authorized and destination account should be pre authorized.

But the ` 'deposit_authorized': True`  for multiple cases:
- Both source and destination accounts without any authorization
- source account authorized and destination account not pre authorized
- destination account authorized and source account unauthorized

**Comment by cindyyan317** [comment]
I think we may have different understanding of this feature.
If destination account has lsfDepositAuth set , we require the preauthorized. But by default , the lsfDepositAuth is not set. means everyone can send fund to destination.
