### ISSUE TITLE
Transaction events delivered out of order

### ISSUE THREAD

**Issue by allanbrondumkr** [XRPLF/clio#833]
If you subscribe to transaction events with https://xrpl.org/subscribe.html#transaction-streams, they are often delivered out of order. The `ledger_index` is always incrementing. But within each `ledger_index`, the value `Meta.TransactionIndex` is not necessarily incrementing. The events seems to be delivered in somewhat random order. The rippled server always delivers the transaction events in the order they are applied to the ledger.

**Comment by cindyyan317** [comment]
Clio does not sort the transactions before publish them out. This is something we can improve. Just out of curiosity, why the order of transactions matters to you? @allanbrondumkr

**Comment by allanbrondumkr** [comment]
@cindyyan317 We have a local representation of part of the on-chain data. And to maintain that local representation we need to apply the changes from transactions applied to the ledger in the same order as on the ledger.

**Comment by allanbrondumkr** [comment]
Simplest case, say you want to track you account balance. Then it is quite important that you see the `AccountRoot` object changes in the order they are applied to the ledger.
