### ISSUE TITLE
Code coverage not accurate due to LOG

### ISSUE THREAD

**Issue by cindyyan317** [XRPLF/clio#845]
We have macro LOG() to avoid the extra evaluation if log is off or log level does not match , which gain performance win👍 . However, small side effect of it is code coverage not accurate due to the log line might not be executed.

![Screenshot 2023-09-12 at 10 01 08](https://github.com/XRPLF/clio/assets/120398799/84a2add5-8fd3-4e91-88c7-6315392fac16)

Need to update the fixture .

**Comment by godexsoft** [comment]
Actually, this is a good side effect. We should not count logging towards code coverage, wdyt?
