### ISSUE TITLE
Move to a newer clang format

### ISSUE THREAD

**Issue by kuznetsss** [XRPLF/clio#848]
We are using quite outdated clang-format-11. E.g. clang-format 14 allows to force east const https://clang.llvm.org/docs/ClangFormatStyleOptions.html#qualifieralignment

**Comment by godexsoft** [comment]
Hopefully also concepts code can be formatted properly now? and some lambdas in our codebase could benefit from better formatting too if we can now tweak it.

**Comment by kuznetsss** [comment]
Try to adjust config to have formatting for
```cpp
if
     <one line code>
ellse
   <one line code>
``` 
statements without `{ }`

**Comment by kuznetsss** [comment]
Force east const style

**Comment by kuznetsss** [comment]
https://github.com/XRPLF/clio/pull/864#discussion_r1331573273

**Comment by kuznetsss** [comment]
https://github.com/XRPLF/clio/pull/864#discussion_r1331587916
https://github.com/XRPLF/clio/pull/864#discussion_r1331595691
