### ISSUE TITLE
Add support in clio server_info to let user know that it is amendment block 

### ISSUE THREAD

**Issue by manojsdoshi** [XRPLF/clio#858]
This would remove the need to repeatedly (every 100 millisecond) log the server is amendment blocked: Reference 

https://github.com/XRPLF/clio/commit/6cfbfda0141a12bb2e65434a9c5502730da3b636

**Comment by godexsoft** [comment]
Actually, i forgot that this was already added but not documented. 
https://github.com/XRPLF/clio/pull/775
