### ISSUE TITLE
Research and make API changes to accommodate XLS-38d: XChainBridge (side chains)

### ISSUE THREAD

**Issue by intelliot** [XRPLF/clio#861]
- https://github.com/XRPLF/rippled/pull/4292

**Comment by cindyyan317** [comment]
New ledger objects and new transactions type are added for this feature.
Clio needs to change:
Prerequisites: make sure xrpl upgrade to [side chains](https://github.com/XRPLF/rippled/pull/4292)
1 ledger_entry, support new ledger types filter
2 account_objects, support new ledger types filter
3 account_tx, support new transactions filter
4 ledger_data, support new ledger types filter

**Comment by cindyyan317** [comment]
This issue will be handled in 
#1090 
#1109
