### ISSUE TITLE
Make a list of all changes that need to be documented between 1.0.4 and today (develop or 2.0)

### ISSUE THREAD

**Issue by intelliot** [XRPLF/clio#862]
The Clio API is documented on xrpl.org. There have been changes since 1.0.4, and they should be documented so that users know how to use the API (and how to upgrade existing integrations, if necessary).

- https://github.com/XRPLF/xrpl-dev-portal/
- https://github.com/XRPLF/clio/compare/1.0.4...develop

**Comment by godexsoft** [comment]
List was created on google docs, tickets to update docs created. Majority will get merged once 2.0 is released.
