### ISSUE TITLE
Duplicate signer_list in account_info to unblock clients (v1)

### ISSUE THREAD

**Issue by cindyyan317** [XRPLF/clio#871]
For API version 1, account_info has "signer_lists" under "account_data" field.
For API version 2, account_info has "signer_list" under root.

Clio supports API version v2 by default. [PR](https://github.com/XRPLF/clio/pull/747/files), in addition, [document](https://xrpl.org/account_info.html) also mentions "signer_lists" should be the same level as "account_data".
However, some clients still expect the v1 format response. To avoid breaking these clients, Clio now applies a temporary fix to duplicate the signer_lists field.

**Comment by ckniffen** [comment]
I tried explicitly specifing the version as 1 and that did not work either before this PR.
