### ISSUE TITLE
Add doxygen to CI

### ISSUE THREAD

**Issue by kuznetsss** [XRPLF/clio#889]
- Automatically generate and upload docs to github pages (or similar). Ideally have docs for develop and releases branches
- Use this theme in our doxygen results https://jothepro.github.io/doxygen-awesome-css/

**Comment by sublimator** [comment]
https://mrdox.com

**Comment by godexsoft** [comment]
This is now working for `develop` docs. Next up in #1239 we should split release docs and developer docs (if we decide it's useful after all).
