### ISSUE TITLE
close_time_human value changes format when called on different systems (mac vs linux)

### ISSUE THREAD

**Issue by manojsdoshi** [XRPLF/clio#903]
There is a difference in the way date are formatted when running on Linux vs Mac 

close_time_human': '2023-Oct-09 04:43:10.000000 UTC
close_time_human': '2023-Oct-09 04:43:10.000000000 UTC

**Comment by godexsoft** [comment]
This value is generated from `ripple::to_string` found in `ripple/basics/chrono.h`. Needs to be fixed on `rippled` side @manojsdoshi 👍
