### ISSUE TITLE
Clio Configuration to Enable Deletion of Old Data

### ISSUE THREAD

**Issue by PaulMoney** [XRPLF/clio#915]
Hello,

I'm wondering whether it's possible to modify the Clio configuration file to enable the deletion of **old** Clio data. Similar to the **online_delete** stanza in the rippled node configuration.

Thanks for any support!

**Comment by godexsoft** [comment]
Hi @PaulMoney, thanks for reaching out.
There is #819 planned with similar functionality. 
For now though, we have removed `online_delete` which was a half-ready feature in Clio. 
While this will not be released with the upcoming Clio 2.0, we will keep it in mind and try to implement it sooner.
