### ISSUE TITLE
Support XLS-40 (DID) in clio

### ISSUE THREAD

**Issue by cindyyan317** [XRPLF/clio#918]
Investigate what Clio needs to do regarding:
https://github.com/XRPLF/rippled/pull/4636
SPEC: https://github.com/XRPLF/XRPL-Standards/pull/136

**Comment by cindyyan317** [comment]
Clio needs to change:
For querying the DID:
1 account_objects
2 ledger_entry
 new ledger object type and tx type: need to update the type filter

**Comment by godexsoft** [comment]
Waiting for `rippled` to create next tag for 2.0.0 with https://github.com/XRPLF/rippled/commit/b421945e717a29e81b029adea576b24cd2068051 included.

**Comment by intelliot** [comment]
Tagged [rippled@2.0.0-b4](https://github.com/XRPLF/rippled/releases/tag/2.0.0-b4)
