### ISSUE TITLE
Move all method implementations out of header and into source files

### ISSUE THREAD

**Issue by cjcobb23** [XRPLF/clio#94]
Sometimes this can't be done because of templating, but otherwise we should do this.

**Comment by godexsoft** [comment]
This is an ongoing issue that should always be kept in mind and does not need a separate github issue for.
The way to do this is thru dependency injection and proper separation of concerns (i.e. the templated code should be abstractions and the implementation details should be normal classes where possible so we can separate implementation into compilation units)
