### ISSUE TITLE
Not exit process if ETL check fail

### ISSUE THREAD

**Issue by cindyyan317** [XRPLF/clio#943]
1 Not exit process if ETL nodes cfg is invalid. Some users may only want to access the existing data not care about the live data.
2 Allow network_id from rippled server_info be empty

**Comment by kuznetsss** [comment]
Maybe add some option to explicitly turn this mode on?
Otherwise it would be easy to miss if there is an error in ETL nodes config.

**Comment by cindyyan317** [comment]
We decided to add "allow_no_etl"  in config to allow user to run Clio without valid ETL.
