### ISSUE TITLE
Move schema definitions to their own file

### ISSUE THREAD

**Issue by cjcobb23** [XRPLF/clio#95]
The Postgres schema is embedded in Pg.cpp, and the Cassandra/Scylla schema is in CassandraBackend.cpp, in the open function. We should move these schema definitions to their own file. We can remove the table name parameter from Cassandra. Users should just create a new keyspace.

**Comment by godexsoft** [comment]
Yes we should separate things properly. However we also will need to slightly redesign and refactor the backend parts eitherway to make then testable. This is again an example of an issues that is some ongoing problem and does not need a separate issue on gh.
