### ISSUE TITLE
Missing `directory` filter for `account_objects`

### ISSUE THREAD

**Issue by mvadari** [XRPLF/clio#970]
This should work (to return a list of directory nodes the account owns), but instead returns an error:
```
{
  "error": "invalidParams",
  "error_code": 31,
  "error_message": "Invalid field 'type'.",
  "status": "error",
  "type": "response",
  "id": 1,
  "request": {
    "id": 1,
    "command": "account_objects",
    "account": "rf1BiGeXwwQoi8Z2ueFYTEXSwuJYfV2Jpn",
    "ledger_index": "validated",
    "type": "directory",
    "limit": 10
  },
  "warnings": [
    {
      "id": 2001,
      "message": "This is a clio server. clio only serves validated data. If you want to talk to rippled, include 'ledger_index':'current' in your request"
    }
  ]
}
```

**Comment by ckniffen** [comment]
It looks like it is not a documented type on xrpl.org.

**Comment by mvadari** [comment]
> It looks like it is not a documented type on xrpl.org.

https://xrpl.org/directorynode.html

**Comment by ckniffen** [comment]
> > It looks like it is not a documented type on xrpl.org.
> 
> https://xrpl.org/directorynode.html

I was looking here. https://xrpl.org/account_objects.html
![account_objects - XRPL org 2023-11-02 15-32-50](https://github.com/XRPLF/clio/assets/464895/458622c2-6438-4689-981b-86087f5d3a1d)

**Comment by mvadari** [comment]
> > > It looks like it is not a documented type on xrpl.org.
> > 
> > 
> > https://xrpl.org/directorynode.html
> 
> I was looking here. https://xrpl.org/account_objects.html ![account_objects - XRPL org 2023-11-02 15-32-50](https://user-images.githubusercontent.com/464895/280120214-458622c2-6438-4689-981b-86087f5d3a1d.png)

It seems that even on rippled this returns an empty array.

**Comment by cindyyan317** [comment]
Yea , I think rippled also does not return directories. The current behaivor also follows the document.
