### ISSUE TITLE
Clio response of ledger_data is missing 'close_time_iso' in the response

### ISSUE THREAD

**Issue by mounikakun** [XRPLF/clio#981]
Issue is observed when tests ran on linux and sample data is from test logs.

Sample request:
`{"method": "ledger_data", "params": [{"binary": false, "ledger_index": 1586615, "limit": 5, "Fee": 20}]}`

Rippled response:
`{'ledger': {'account_hash': 'BA5147B1E11F1867DB103A77C0705C33E82C75D40F4A06572BD25F04540C5F71', 'close_flags': 0, 'close_time': 753191780, 'close_time_human': '2023-Nov-13 11:56:20.000000000 UTC', '**close_time_iso**': '2023-11-13T11:56:20Z', 'close_time_resolution': 10, 'closed': True, 'ledger_hash': '27E192DCEC0C0513F77EC988B0D4F822F5AF00F84BBB7DC8D38EAF42F981383F', 'ledger_index': '1586615', 'parent_close_time': 753191773, 'parent_hash': 'D7871B261697DB1589982D7203AD35A95E65DC1B3CB980286AD61B9C37397B5A', 'total_coins': '99999963272798172', 'transaction_hash': '955F386D244EFC1BF788B7D5C76C78EA18A73AAAC2FFCD8FEB829A48C514E020'}, 'ledger_hash': '27E192DCEC0C0513F77EC988B0D4F822F5AF00F84BBB7DC8D38EAF42F981383F', 'ledger_index': 1586615, 'marker': '0000484212608DEA2595A392E3D8368D28B9107F52159DE260A2F0F9CE214E02', 'state': [{'Account': 'rnQuK4LDxn9UVzoxPstxkGcabmEFTd8RV6', 'Flags': 0, 'LedgerEntryType': 'Ticket', 'OwnerNode': '3', 'PreviousTxnID': '8ACBC74864E7DEC65B8E11DCCF9FF2471B8FCFD4095AA55AA4F21470655EF61B', 'PreviousTxnLgrSeq': 1296757, 'TicketSequence': 1296879, 'index': '000016F3EEA1A9C1067E966020878E1FE83B9C25D1597807F7441587A1A1D0B9'}, {'Account': 'rK1ipxhgHZL2NrGoftX7tWaxgG3ybe5btN', 'Balance': '39999980', 'Flags': 0, 'LedgerEntryType': 'AccountRoot', 'OwnerCount': 0, 'PreviousTxnID': 'A646E7641BB7EBD7D29A6ED6A458489DA54CB3E98B86B1B5336B5D1152A13A42', 'PreviousTxnLgrSeq': 191711, 'Sequence': 191708, 'index': '000029337777A8005FD1DC5909E1F72810EF4CD74B295821ADE27A492567CCAD'}, {'Flags': 0, 'Indexes': ['2C64F544047C515AD196758C0A0DB184494B06552A274E123F584DB9C178D3A2'], 'LedgerEntryType': 'DirectoryNode', 'Owner': 'rDgfK69Z1aNa4uX97eCuD5Mdu7sXvAShCS', 'RootIndex': '00003DEDB620647EDEA1D1AE153EDBEBFD102642E3954F9AF5CBD6754050855D', 'index': '00003DEDB620647EDEA1D1AE153EDBEBFD102642E3954F9AF5CBD6754050855D'}, {'Account': 'rJAYJvxnvyBm555RE4UYjyK1QkBADr72Rp', 'Balance': '39989980', 'Flags': 0, 'LedgerEntryType': 'AccountRoot', 'OwnerCount': 0, 'PreviousTxnID': '10A0B2DD1DD8E5933AE4702E4CB1006030D73D6ADAEA46E1102413DEB82CF878', 'PreviousTxnLgrSeq': 199988, 'Sequence': 199987, 'index': '00003F6724059CBBEFEADC1C3DA3BC49A0B99280662B733A67C9C96DD5453B21'}, {'Account': 'rDjzf81LNwGMX1Q4rsoHCu6i8GYQoA2aca', 'Flags': 0, 'LedgerEntryType': 'Ticket', 'OwnerNode': '5', 'PreviousTxnID': 'A7FE1E6658A4D5D346843321AFA7013883C4C3094552F0C55A95C51CA88B6450', 'PreviousTxnLgrSeq': 425736, 'TicketSequence': 425921, 'index': '0000408B96E95556516911CD2E41E78F774A744305B0DADE25E3A21DFFD78779'}], 'validated': True, 'status': 'success'}
`

Clio response:
`{'ledger_hash': '27E192DCEC0C0513F77EC988B0D4F822F5AF00F84BBB7DC8D38EAF42F981383F', 'ledger_index': 1586615, 'validated': True, 'state': [{'Account': 'rnQuK4LDxn9UVzoxPstxkGcabmEFTd8RV6', 'Flags': 0, 'LedgerEntryType': 'Ticket', 'OwnerNode': '3', 'PreviousTxnID': '8ACBC74864E7DEC65B8E11DCCF9FF2471B8FCFD4095AA55AA4F21470655EF61B', 'PreviousTxnLgrSeq': 1296757, 'TicketSequence': 1296879, 'index': '000016F3EEA1A9C1067E966020878E1FE83B9C25D1597807F7441587A1A1D0B9'}, {'Account': 'rK1ipxhgHZL2NrGoftX7tWaxgG3ybe5btN', 'Balance': '39999980', 'Flags': 0, 'LedgerEntryType': 'AccountRoot', 'OwnerCount': 0, 'PreviousTxnID': 'A646E7641BB7EBD7D29A6ED6A458489DA54CB3E98B86B1B5336B5D1152A13A42', 'PreviousTxnLgrSeq': 191711, 'Sequence': 191708, 'index': '000029337777A8005FD1DC5909E1F72810EF4CD74B295821ADE27A492567CCAD'}, {'Flags': 0, 'Indexes': ['2C64F544047C515AD196758C0A0DB184494B06552A274E123F584DB9C178D3A2'], 'LedgerEntryType': 'DirectoryNode', 'Owner': 'rDgfK69Z1aNa4uX97eCuD5Mdu7sXvAShCS', 'RootIndex': '00003DEDB620647EDEA1D1AE153EDBEBFD102642E3954F9AF5CBD6754050855D', 'index': '00003DEDB620647EDEA1D1AE153EDBEBFD102642E3954F9AF5CBD6754050855D'}, {'Account': 'rJAYJvxnvyBm555RE4UYjyK1QkBADr72Rp', 'Balance': '39989980', 'Flags': 0, 'LedgerEntryType': 'AccountRoot', 'OwnerCount': 0, 'PreviousTxnID': '10A0B2DD1DD8E5933AE4702E4CB1006030D73D6ADAEA46E1102413DEB82CF878', 'PreviousTxnLgrSeq': 199988, 'Sequence': 199987, 'index': '00003F6724059CBBEFEADC1C3DA3BC49A0B99280662B733A67C9C96DD5453B21'}, {'Account': 'rDjzf81LNwGMX1Q4rsoHCu6i8GYQoA2aca', 'Flags': 0, 'LedgerEntryType': 'Ticket', 'OwnerNode': '5', 'PreviousTxnID': 'A7FE1E6658A4D5D346843321AFA7013883C4C3094552F0C55A95C51CA88B6450', 'PreviousTxnLgrSeq': 425736, 'TicketSequence': 425921, 'index': '0000408B96E95556516911CD2E41E78F774A744305B0DADE25E3A21DFFD78779'}], 'ledger': {'account_hash': 'BA5147B1E11F1867DB103A77C0705C33E82C75D40F4A06572BD25F04540C5F71', 'close_flags': 0, 'close_time': 753191780, 'close_time_human': '2023-Nov-13 11:56:20.000000000 UTC', 'close_time_resolution': 10, 'ledger_hash': '27E192DCEC0C0513F77EC988B0D4F822F5AF00F84BBB7DC8D38EAF42F981383F', 'ledger_index': '1586615', 'parent_close_time': 753191773, 'parent_hash': 'D7871B261697DB1589982D7203AD35A95E65DC1B3CB980286AD61B9C37397B5A', 'total_coins': '99999963272798172', 'transaction_hash': '955F386D244EFC1BF788B7D5C76C78EA18A73AAAC2FFCD8FEB829A48C514E020', 'closed': True}, 'marker': '0000408B96E95556516911CD2E41E78F774A744305B0DADE25E3A21DFFD78779', 'status': 'success'}
`

**Comment by cindyyan317** [comment]
I think this field is newly introduced from https://github.com/XRPLF/rippled/pull/4775/files

**Comment by cindyyan317** [comment]
Fixed at #992
