### ISSUE TITLE
Update docs for account_tx with tx_type AMM 

### ISSUE THREAD

**Issue by mounikakun** [XRPLF/clio#986]
As per the [docs](https://xrpl.org/account_tx.html#account_tx) account_tx with tx_type AMM is not acceptable. Reason might be related to release of AMM.

**Comment by godexsoft** [comment]
PR ready https://github.com/XRPLF/xrpl-dev-portal/pull/2337. 
Closing this issue as we now have a PR for this on the xrpl-dev-portal.
