### ISSUE TITLE
nft_by_issuer return NFTs with invalid marker is not erroring out or returning empty nfts.

### ISSUE THREAD

**Issue by mounikakun** [XRPLF/clio#991]
Request:
`{
    "method": "nfts_by_issuer",
    "params": [
        {
            "issuer": "rPpDg7RwpfTEEDcJpCqcXvwNbn8sDzqNvz",
            "limit":10
        }
    ]
}`

Response:
`{
    "result": {
        "issuer": "rPpDg7RwpfTEEDcJpCqcXvwNbn8sDzqNvz",
        "limit": 10,
        "ledger_index": 1658384,
        "nfts": [
            {
                "nft_id": "00000000F18DC4B6490A415FF9116C7D77754CCB00286D786A3BE72B00194D90",
                "ledger_index": 1658260,
                "owner": "rPpDg7RwpfTEEDcJpCqcXvwNbn8sDzqNvz",
                "is_burned": false,
                "uri": "",
                "flags": 0,
                "transfer_fee": 0,
                "issuer": "rPpDg7RwpfTEEDcJpCqcXvwNbn8sDzqNvz",
                "nft_taxon": 0,
                "nft_serial": 1658256
            },
            {
                "nft_id": "00000000F18DC4B6490A415FF9116C7D77754CCB00286D785356162A00194D8F",
                "ledger_index": 1658259,
                "owner": "rPpDg7RwpfTEEDcJpCqcXvwNbn8sDzqNvz",
                "is_burned": false,
                "uri": "",
                "flags": 0,
                "transfer_fee": 0,
                "issuer": "rPpDg7RwpfTEEDcJpCqcXvwNbn8sDzqNvz",
                "nft_taxon": 0,
                "nft_serial": 1658255
            },
            {
                "nft_id": "00000000F18DC4B6490A415FF9116C7D77754CCB00286D783C70452900194D8E",
                "ledger_index": 1658257,
                "owner": "rPpDg7RwpfTEEDcJpCqcXvwNbn8sDzqNvz",
                "is_burned": false,
                "uri": "",
                "flags": 0,
                "transfer_fee": 0,
                "issuer": "rPpDg7RwpfTEEDcJpCqcXvwNbn8sDzqNvz",
                "nft_taxon": 0,
                "nft_serial": 1658254
            },
            {
                "nft_id": "00000000F18DC4B6490A415FF9116C7D77754CCB00286D78258A742800194D8D",
                "ledger_index": 1658256,
                "owner": "rPpDg7RwpfTEEDcJpCqcXvwNbn8sDzqNvz",
                "is_burned": false,
                "uri": "",
                "flags": 0,
                "transfer_fee": 0,
                "issuer": "rPpDg7RwpfTEEDcJpCqcXvwNbn8sDzqNvz",
                "nft_taxon": 0,
                "nft_serial": 1658253
            },
            {
                "nft_id": "00000000F18DC4B6490A415FF9116C7D77754CCB00286D780EA4A32700194D8C",
                "ledger_index": 1658255,
                "owner": "rPpDg7RwpfTEEDcJpCqcXvwNbn8sDzqNvz",
                "is_burned": false,
                "uri": "",
                "flags": 0,
                "transfer_fee": 0,
                "issuer": "rPpDg7RwpfTEEDcJpCqcXvwNbn8sDzqNvz",
                "nft_taxon": 0,
                "nft_serial": 1658252
            },
            {
                "nft_id": "00000000F18DC4B6490A415FF9116C7D77754CCB00286D786E5BEC2000194D85",
                "ledger_index": 1658247,
                "owner": "rPpDg7RwpfTEEDcJpCqcXvwNbn8sDzqNvz",
                "is_burned": false,
                "uri": "",
                "flags": 0,
                "transfer_fee": 0,
                "issuer": "rPpDg7RwpfTEEDcJpCqcXvwNbn8sDzqNvz",
                "nft_taxon": 0,
                "nft_serial": 1658245
            },
            {
                "nft_id": "00000000F18DC4B6490A415FF9116C7D77754CCB00286D7857761B1F00194D84",
                "ledger_index": 1658246,
                "owner": "rPpDg7RwpfTEEDcJpCqcXvwNbn8sDzqNvz",
                "is_burned": false,
                "uri": "",
                "flags": 0,
                "transfer_fee": 0,
                "issuer": "rPpDg7RwpfTEEDcJpCqcXvwNbn8sDzqNvz",
                "nft_taxon": 0,
                "nft_serial": 1658244
            },
            {
                "nft_id": "00000000F18DC4B6490A415FF9116C7D77754CCB00286D7840904A1E00194D83",
                "ledger_index": 1658245,
                "owner": "rPpDg7RwpfTEEDcJpCqcXvwNbn8sDzqNvz",
                "is_burned": false,
                "uri": "",
                "flags": 0,
                "transfer_fee": 0,
                "issuer": "rPpDg7RwpfTEEDcJpCqcXvwNbn8sDzqNvz",
                "nft_taxon": 0,
                "nft_serial": 1658243
            },
            {
                "nft_id": "00000000F18DC4B6490A415FF9116C7D77754CCB00286D7829AA791D00194D82",
                "ledger_index": 1658243,
                "owner": "rPpDg7RwpfTEEDcJpCqcXvwNbn8sDzqNvz",
                "is_burned": false,
                "uri": "",
                "flags": 0,
                "transfer_fee": 0,
                "issuer": "rPpDg7RwpfTEEDcJpCqcXvwNbn8sDzqNvz",
                "nft_taxon": 0,
                "nft_serial": 1658242
            },
            {
                "nft_id": "00000000F18DC4B6490A415FF9116C7D77754CCB00286D7812C4A81C00194D81",
                "ledger_index": 1658242,
                "owner": "rPpDg7RwpfTEEDcJpCqcXvwNbn8sDzqNvz",
                "is_burned": false,
                "uri": "",
                "flags": 0,
                "transfer_fee": 0,
                "issuer": "rPpDg7RwpfTEEDcJpCqcXvwNbn8sDzqNvz",
                "nft_taxon": 0,
                "nft_serial": 1658241
            }
        ],
        "validated": true,
        "marker": "00000000F18DC4B6490A415FF9116C7D77754CCB00286D786E5BEC2000194D85",
        "status": "success"
    },
    "warnings": [
        {
            "id": 2001,
            "message": "This is a clio server. clio only serves validated data. If you want to talk to rippled, include 'ledger_index':'current' in your request"
        }
    ]
}`

Actual marker from the response is  `"marker": "00000000F18DC4B6490A415FF9116C7D77754CCB00286D786E5BEC2000194D85"` but using different marker in the request
`"marker": "000000004280875B1B0435334FCA9CC68152860A5DF34BEBABC033520015C2B7"`

Request:
`{
    "method": "nfts_by_issuer",
    "params": [
        {
            "issuer": "rPpDg7RwpfTEEDcJpCqcXvwNbn8sDzqNvz",
            "limit":10,
            "marker": "000000004280875B1B0435334FCA9CC68152860A5DF34BEBABC033520015C2B7"
        }
    ]
}`

Response:
`{
    "result": {
        "issuer": "rPpDg7RwpfTEEDcJpCqcXvwNbn8sDzqNvz",
        "limit": 10,
        "ledger_index": 1658415,
        "nfts": [
            {
                "nft_id": "00000000F18DC4B6490A415FF9116C7D77754CCB00286D786A3BE72B00194D90",
                "ledger_index": 1658260,
                "owner": "rPpDg7RwpfTEEDcJpCqcXvwNbn8sDzqNvz",
                "is_burned": false,
                "uri": "",
                "flags": 0,
                "transfer_fee": 0,
                "issuer": "rPpDg7RwpfTEEDcJpCqcXvwNbn8sDzqNvz",
                "nft_taxon": 0,
                "nft_serial": 1658256
            },
            {
                "nft_id": "00000000F18DC4B6490A415FF9116C7D77754CCB00286D785356162A00194D8F",
                "ledger_index": 1658259,
                "owner": "rPpDg7RwpfTEEDcJpCqcXvwNbn8sDzqNvz",
                "is_burned": false,
                "uri": "",
                "flags": 0,
                "transfer_fee": 0,
                "issuer": "rPpDg7RwpfTEEDcJpCqcXvwNbn8sDzqNvz",
                "nft_taxon": 0,
                "nft_serial": 1658255
            },
            {
                "nft_id": "00000000F18DC4B6490A415FF9116C7D77754CCB00286D783C70452900194D8E",
                "ledger_index": 1658257,
                "owner": "rPpDg7RwpfTEEDcJpCqcXvwNbn8sDzqNvz",
                "is_burned": false,
                "uri": "",
                "flags": 0,
                "transfer_fee": 0,
                "issuer": "rPpDg7RwpfTEEDcJpCqcXvwNbn8sDzqNvz",
                "nft_taxon": 0,
                "nft_serial": 1658254
            },
            {
                "nft_id": "00000000F18DC4B6490A415FF9116C7D77754CCB00286D78258A742800194D8D",
                "ledger_index": 1658256,
                "owner": "rPpDg7RwpfTEEDcJpCqcXvwNbn8sDzqNvz",
                "is_burned": false,
                "uri": "",
                "flags": 0,
                "transfer_fee": 0,
                "issuer": "rPpDg7RwpfTEEDcJpCqcXvwNbn8sDzqNvz",
                "nft_taxon": 0,
                "nft_serial": 1658253
            },
            {
                "nft_id": "00000000F18DC4B6490A415FF9116C7D77754CCB00286D780EA4A32700194D8C",
                "ledger_index": 1658255,
                "owner": "rPpDg7RwpfTEEDcJpCqcXvwNbn8sDzqNvz",
                "is_burned": false,
                "uri": "",
                "flags": 0,
                "transfer_fee": 0,
                "issuer": "rPpDg7RwpfTEEDcJpCqcXvwNbn8sDzqNvz",
                "nft_taxon": 0,
                "nft_serial": 1658252
            },
            {
                "nft_id": "00000000F18DC4B6490A415FF9116C7D77754CCB00286D786E5BEC2000194D85",
                "ledger_index": 1658247,
                "owner": "rPpDg7RwpfTEEDcJpCqcXvwNbn8sDzqNvz",
                "is_burned": false,
                "uri": "",
                "flags": 0,
                "transfer_fee": 0,
                "issuer": "rPpDg7RwpfTEEDcJpCqcXvwNbn8sDzqNvz",
                "nft_taxon": 0,
                "nft_serial": 1658245
            },
            {
                "nft_id": "00000000F18DC4B6490A415FF9116C7D77754CCB00286D7857761B1F00194D84",
                "ledger_index": 1658246,
                "owner": "rPpDg7RwpfTEEDcJpCqcXvwNbn8sDzqNvz",
                "is_burned": false,
                "uri": "",
                "flags": 0,
                "transfer_fee": 0,
                "issuer": "rPpDg7RwpfTEEDcJpCqcXvwNbn8sDzqNvz",
                "nft_taxon": 0,
                "nft_serial": 1658244
            },
            {
                "nft_id": "00000000F18DC4B6490A415FF9116C7D77754CCB00286D7840904A1E00194D83",
                "ledger_index": 1658245,
                "owner": "rPpDg7RwpfTEEDcJpCqcXvwNbn8sDzqNvz",
                "is_burned": false,
                "uri": "",
                "flags": 0,
                "transfer_fee": 0,
                "issuer": "rPpDg7RwpfTEEDcJpCqcXvwNbn8sDzqNvz",
                "nft_taxon": 0,
                "nft_serial": 1658243
            },
            {
                "nft_id": "00000000F18DC4B6490A415FF9116C7D77754CCB00286D7829AA791D00194D82",
                "ledger_index": 1658243,
                "owner": "rPpDg7RwpfTEEDcJpCqcXvwNbn8sDzqNvz",
                "is_burned": false,
                "uri": "",
                "flags": 0,
                "transfer_fee": 0,
                "issuer": "rPpDg7RwpfTEEDcJpCqcXvwNbn8sDzqNvz",
                "nft_taxon": 0,
                "nft_serial": 1658242
            },
            {
                "nft_id": "00000000F18DC4B6490A415FF9116C7D77754CCB00286D7812C4A81C00194D81",
                "ledger_index": 1658242,
                "owner": "rPpDg7RwpfTEEDcJpCqcXvwNbn8sDzqNvz",
                "is_burned": false,
                "uri": "",
                "flags": 0,
                "transfer_fee": 0,
                "issuer": "rPpDg7RwpfTEEDcJpCqcXvwNbn8sDzqNvz",
                "nft_taxon": 0,
                "nft_serial": 1658241
            }
        ],
        "validated": true,
        "marker": "00000000F18DC4B6490A415FF9116C7D77754CCB00286D786E5BEC2000194D85",
        "status": "success"
    },
    "warnings": [
        {
            "id": 2001,
            "message": "This is a clio server. clio only serves validated data. If you want to talk to rippled, include 'ledger_index':'current' in your request"
        }
    ]
}`

**Comment by cindyyan317** [comment]
The requests are not aware of each other. Thus the request does not know if the marker is returned by the previous request or not.
When the marker is provided in request, we return the nfts whose nft_id is larger than the marker. As long as the marker is a valid uint256 , it is valid for query.

**Comment by cindyyan317** [comment]
We decided not to add the check for now. We only check if format is correct but not check if marker belong to this account. To check the ownership of nft, we need to db access, it does not worth to add one extra db query just for this edge case.
